issuer: http://dex:5556/dex

storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db

web:
  http: 0.0.0.0:5556

oauth2:
  responseTypes: [code]
  skipApprovalScreen: true
  grantTypes:
    - authorization_code
    - password

enablePasswordDB: true

staticClients:
  - id: nebu-gateway
    name: "Nebu Gateway"
    secret: nebu-dev-secret
    redirectURIs:
      - "http://localhost:8008/_matrix/client/v3/login/sso/redirect/oidc"

  - id: nebu-admin
    name: "Nebu Admin UI"
    secret: nebu-admin-secret
    redirectURIs:
      - "http://localhost:8080/admin/callback"

staticPasswords:
  - email: "kai@example.com"
    hash: "$2a$10$E4ye88CWSgoigClMVojmGOu.gHlKe7L7RRf07QWZ60aZmZ7Rfak/6"
    username: "kai"
    userID: "00000000-0000-0000-0000-000000000001"
    groups:
      - instance_admin

  - email: "compliance@example.com"
    hash: "$2a$10$E4ye88CWSgoigClMVojmGOu.gHlKe7L7RRf07QWZ60aZmZ7Rfak/6"
    username: "compliance"
    userID: "00000000-0000-0000-0000-000000000002"
    groups:
      - compliance_officer

  - email: "alex@example.com"
    hash: "$2a$10$E4ye88CWSgoigClMVojmGOu.gHlKe7L7RRf07QWZ60aZmZ7Rfak/6"
    username: "alex"
    userID: "00000000-0000-0000-0000-000000000003"
    groups:
      - user
