apiVersion: v1
kind: Service
metadata:
  name: {{ include "nebu.fullname" . }}-core
  labels:
    {{- include "nebu.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 4000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nebu.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: core
