{{- if .Values.autoscaling.gateway.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nebu.fullname" . }}-gateway
  labels:
    {{- include "nebu.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nebu.fullname" . }}-gateway
  minReplicas: {{ .Values.autoscaling.gateway.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.gateway.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.gateway.targetCPUUtilizationPercentage }}
{{- end }}
