# ── Stackit Logs ──────────────────────────────────────────────────────────────
# Managed Loki-based log aggregation. Fluent Bit on the VM ships nebu.service logs here.
# Set enable_logs = true in terraform.tfvars to activate.
#
# The access token is generated by OpenTofu and injected into cloud-init at first boot —
# no manual Portal step required.

resource "stackit_logs_instance" "nebu" {
  count          = var.enable_logs ? 1 : 0
  project_id     = var.stackit_project_id
  region         = var.region
  display_name   = "nebu-${var.environment}-logs"
  retention_days = var.logs_retention_days
}

resource "stackit_logs_access_token" "nebu" {
  count        = var.enable_logs ? 1 : 0
  project_id   = var.stackit_project_id
  instance_id  = stackit_logs_instance.nebu[0].instance_id
  region       = var.region
  display_name = "nebu-${var.environment}-fluent-bit"
  permissions  = ["write"]
}
