// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: core.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreService_SendEvent_FullMethodName        = "/core.CoreService/SendEvent"
	CoreService_CreateRoom_FullMethodName       = "/core.CoreService/CreateRoom"
	CoreService_JoinRoom_FullMethodName         = "/core.CoreService/JoinRoom"
	CoreService_GetMessages_FullMethodName      = "/core.CoreService/GetMessages"
	CoreService_SetPresence_FullMethodName      = "/core.CoreService/SetPresence"
	CoreService_SetTyping_FullMethodName        = "/core.CoreService/SetTyping"
	CoreService_ValidateToken_FullMethodName    = "/core.CoreService/ValidateToken"
	CoreService_GetPendingEvents_FullMethodName = "/core.CoreService/GetPendingEvents"
	CoreService_EventBus_FullMethodName         = "/core.CoreService/EventBus"
	CoreService_GetMetrics_FullMethodName       = "/core.CoreService/GetMetrics"
	CoreService_GetRoomState_FullMethodName     = "/core.CoreService/GetRoomState"
	CoreService_InviteUser_FullMethodName       = "/core.CoreService/InviteUser"
	CoreService_SetPowerLevels_FullMethodName   = "/core.CoreService/SetPowerLevels"
	CoreService_SendReceipt_FullMethodName      = "/core.CoreService/SendReceipt"
	CoreService_GetInitialSync_FullMethodName   = "/core.CoreService/GetInitialSync"
	CoreService_GetSyncDelta_FullMethodName     = "/core.CoreService/GetSyncDelta"
)

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoreService: all gRPC operations between Go Gateway and Elixir Core.
// Go is always the client; Elixir is always the server.
type CoreServiceClient interface {
	// Matrix operations (unary request/response)
	SendEvent(ctx context.Context, in *SendEventRequest, opts ...grpc.CallOption) (*SendEventResponse, error)
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error)
	JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error)
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	SetPresence(ctx context.Context, in *SetPresenceRequest, opts ...grpc.CallOption) (*SetPresenceResponse, error)
	SetTyping(ctx context.Context, in *SetTypingRequest, opts ...grpc.CallOption) (*SetTypingResponse, error)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	GetPendingEvents(ctx context.Context, in *GetPendingEventsRequest, opts ...grpc.CallOption) (*GetPendingEventsResponse, error)
	// Event Bus — server-streaming, one stream per Go instance
	EventBus(ctx context.Context, in *EventBusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// GetMetrics — Admin Dashboard live metrics (Epic 3 skeleton; full implementation Epic 4)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	// GetRoomState — unary: Go queries current room members + metadata
	GetRoomState(ctx context.Context, in *GetRoomStateRequest, opts ...grpc.CallOption) (*GetRoomStateResponse, error)
	// InviteUser — invite a user to a room
	InviteUser(ctx context.Context, in *InviteUserRequest, opts ...grpc.CallOption) (*InviteUserResponse, error)
	// SetPowerLevels — update room power levels (caller must have change_state power)
	SetPowerLevels(ctx context.Context, in *SetPowerLevelsRequest, opts ...grpc.CallOption) (*SetPowerLevelsResponse, error)
	// SendReceipt — persists a read receipt for a user in a room
	SendReceipt(ctx context.Context, in *SendReceiptRequest, opts ...grpc.CallOption) (*SendReceiptResponse, error)
	// GetInitialSync — returns full state snapshot for all of a user's joined rooms
	GetInitialSync(ctx context.Context, in *GetInitialSyncRequest, opts ...grpc.CallOption) (*GetInitialSyncResponse, error)
	// GetSyncDelta — incremental sync with long-polling; returns events after since_token
	GetSyncDelta(ctx context.Context, in *GetSyncDeltaRequest, opts ...grpc.CallOption) (*GetSyncDeltaResponse, error)
}

type coreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServiceClient(cc grpc.ClientConnInterface) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) SendEvent(ctx context.Context, in *SendEventRequest, opts ...grpc.CallOption) (*SendEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEventResponse)
	err := c.cc.Invoke(ctx, CoreService_SendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoomResponse)
	err := c.cc.Invoke(ctx, CoreService_CreateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinRoomResponse)
	err := c.cc.Invoke(ctx, CoreService_JoinRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, CoreService_GetMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SetPresence(ctx context.Context, in *SetPresenceRequest, opts ...grpc.CallOption) (*SetPresenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPresenceResponse)
	err := c.cc.Invoke(ctx, CoreService_SetPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SetTyping(ctx context.Context, in *SetTypingRequest, opts ...grpc.CallOption) (*SetTypingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTypingResponse)
	err := c.cc.Invoke(ctx, CoreService_SetTyping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, CoreService_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetPendingEvents(ctx context.Context, in *GetPendingEventsRequest, opts ...grpc.CallOption) (*GetPendingEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingEventsResponse)
	err := c.cc.Invoke(ctx, CoreService_GetPendingEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) EventBus(ctx context.Context, in *EventBusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoreService_ServiceDesc.Streams[0], CoreService_EventBus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventBusRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreService_EventBusClient = grpc.ServerStreamingClient[Event]

func (c *coreServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, CoreService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetRoomState(ctx context.Context, in *GetRoomStateRequest, opts ...grpc.CallOption) (*GetRoomStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomStateResponse)
	err := c.cc.Invoke(ctx, CoreService_GetRoomState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) InviteUser(ctx context.Context, in *InviteUserRequest, opts ...grpc.CallOption) (*InviteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteUserResponse)
	err := c.cc.Invoke(ctx, CoreService_InviteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SetPowerLevels(ctx context.Context, in *SetPowerLevelsRequest, opts ...grpc.CallOption) (*SetPowerLevelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPowerLevelsResponse)
	err := c.cc.Invoke(ctx, CoreService_SetPowerLevels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SendReceipt(ctx context.Context, in *SendReceiptRequest, opts ...grpc.CallOption) (*SendReceiptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendReceiptResponse)
	err := c.cc.Invoke(ctx, CoreService_SendReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetInitialSync(ctx context.Context, in *GetInitialSyncRequest, opts ...grpc.CallOption) (*GetInitialSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInitialSyncResponse)
	err := c.cc.Invoke(ctx, CoreService_GetInitialSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetSyncDelta(ctx context.Context, in *GetSyncDeltaRequest, opts ...grpc.CallOption) (*GetSyncDeltaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSyncDeltaResponse)
	err := c.cc.Invoke(ctx, CoreService_GetSyncDelta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServiceServer is the server API for CoreService service.
// All implementations must embed UnimplementedCoreServiceServer
// for forward compatibility.
//
// CoreService: all gRPC operations between Go Gateway and Elixir Core.
// Go is always the client; Elixir is always the server.
type CoreServiceServer interface {
	// Matrix operations (unary request/response)
	SendEvent(context.Context, *SendEventRequest) (*SendEventResponse, error)
	CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error)
	JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error)
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	SetPresence(context.Context, *SetPresenceRequest) (*SetPresenceResponse, error)
	SetTyping(context.Context, *SetTypingRequest) (*SetTypingResponse, error)
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	GetPendingEvents(context.Context, *GetPendingEventsRequest) (*GetPendingEventsResponse, error)
	// Event Bus — server-streaming, one stream per Go instance
	EventBus(*EventBusRequest, grpc.ServerStreamingServer[Event]) error
	// GetMetrics — Admin Dashboard live metrics (Epic 3 skeleton; full implementation Epic 4)
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	// GetRoomState — unary: Go queries current room members + metadata
	GetRoomState(context.Context, *GetRoomStateRequest) (*GetRoomStateResponse, error)
	// InviteUser — invite a user to a room
	InviteUser(context.Context, *InviteUserRequest) (*InviteUserResponse, error)
	// SetPowerLevels — update room power levels (caller must have change_state power)
	SetPowerLevels(context.Context, *SetPowerLevelsRequest) (*SetPowerLevelsResponse, error)
	// SendReceipt — persists a read receipt for a user in a room
	SendReceipt(context.Context, *SendReceiptRequest) (*SendReceiptResponse, error)
	// GetInitialSync — returns full state snapshot for all of a user's joined rooms
	GetInitialSync(context.Context, *GetInitialSyncRequest) (*GetInitialSyncResponse, error)
	// GetSyncDelta — incremental sync with long-polling; returns events after since_token
	GetSyncDelta(context.Context, *GetSyncDeltaRequest) (*GetSyncDeltaResponse, error)
	mustEmbedUnimplementedCoreServiceServer()
}

// UnimplementedCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServiceServer struct{}

func (UnimplementedCoreServiceServer) SendEvent(context.Context, *SendEventRequest) (*SendEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedCoreServiceServer) CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRoom not implemented")
}
func (UnimplementedCoreServiceServer) JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinRoom not implemented")
}
func (UnimplementedCoreServiceServer) GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedCoreServiceServer) SetPresence(context.Context, *SetPresenceRequest) (*SetPresenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPresence not implemented")
}
func (UnimplementedCoreServiceServer) SetTyping(context.Context, *SetTypingRequest) (*SetTypingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTyping not implemented")
}
func (UnimplementedCoreServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedCoreServiceServer) GetPendingEvents(context.Context, *GetPendingEventsRequest) (*GetPendingEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingEvents not implemented")
}
func (UnimplementedCoreServiceServer) EventBus(*EventBusRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method EventBus not implemented")
}
func (UnimplementedCoreServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedCoreServiceServer) GetRoomState(context.Context, *GetRoomStateRequest) (*GetRoomStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoomState not implemented")
}
func (UnimplementedCoreServiceServer) InviteUser(context.Context, *InviteUserRequest) (*InviteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteUser not implemented")
}
func (UnimplementedCoreServiceServer) SetPowerLevels(context.Context, *SetPowerLevelsRequest) (*SetPowerLevelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPowerLevels not implemented")
}
func (UnimplementedCoreServiceServer) SendReceipt(context.Context, *SendReceiptRequest) (*SendReceiptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendReceipt not implemented")
}
func (UnimplementedCoreServiceServer) GetInitialSync(context.Context, *GetInitialSyncRequest) (*GetInitialSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInitialSync not implemented")
}
func (UnimplementedCoreServiceServer) GetSyncDelta(context.Context, *GetSyncDeltaRequest) (*GetSyncDeltaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncDelta not implemented")
}
func (UnimplementedCoreServiceServer) mustEmbedUnimplementedCoreServiceServer() {}
func (UnimplementedCoreServiceServer) testEmbeddedByValue()                     {}

// UnsafeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServiceServer will
// result in compilation errors.
type UnsafeCoreServiceServer interface {
	mustEmbedUnimplementedCoreServiceServer()
}

func RegisterCoreServiceServer(s grpc.ServiceRegistrar, srv CoreServiceServer) {
	// If the following call panics, it indicates UnimplementedCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreService_ServiceDesc, srv)
}

func _CoreService_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_SendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SendEvent(ctx, req.(*SendEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_CreateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_JoinRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).JoinRoom(ctx, req.(*JoinRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SetPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SetPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_SetPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SetPresence(ctx, req.(*SetPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SetTyping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTypingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SetTyping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_SetTyping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SetTyping(ctx, req.(*SetTypingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetPendingEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetPendingEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetPendingEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetPendingEvents(ctx, req.(*GetPendingEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_EventBus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventBusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServiceServer).EventBus(m, &grpc.GenericServerStream[EventBusRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreService_EventBusServer = grpc.ServerStreamingServer[Event]

func _CoreService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetRoomState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetRoomState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetRoomState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetRoomState(ctx, req.(*GetRoomStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_InviteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).InviteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_InviteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).InviteUser(ctx, req.(*InviteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SetPowerLevels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPowerLevelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SetPowerLevels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_SetPowerLevels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SetPowerLevels(ctx, req.(*SetPowerLevelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SendReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SendReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_SendReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SendReceipt(ctx, req.(*SendReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetInitialSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInitialSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetInitialSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetInitialSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetInitialSync(ctx, req.(*GetInitialSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetSyncDelta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyncDeltaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetSyncDelta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetSyncDelta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetSyncDelta(ctx, req.(*GetSyncDeltaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreService_ServiceDesc is the grpc.ServiceDesc for CoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEvent",
			Handler:    _CoreService_SendEvent_Handler,
		},
		{
			MethodName: "CreateRoom",
			Handler:    _CoreService_CreateRoom_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _CoreService_JoinRoom_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _CoreService_GetMessages_Handler,
		},
		{
			MethodName: "SetPresence",
			Handler:    _CoreService_SetPresence_Handler,
		},
		{
			MethodName: "SetTyping",
			Handler:    _CoreService_SetTyping_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _CoreService_ValidateToken_Handler,
		},
		{
			MethodName: "GetPendingEvents",
			Handler:    _CoreService_GetPendingEvents_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _CoreService_GetMetrics_Handler,
		},
		{
			MethodName: "GetRoomState",
			Handler:    _CoreService_GetRoomState_Handler,
		},
		{
			MethodName: "InviteUser",
			Handler:    _CoreService_InviteUser_Handler,
		},
		{
			MethodName: "SetPowerLevels",
			Handler:    _CoreService_SetPowerLevels_Handler,
		},
		{
			MethodName: "SendReceipt",
			Handler:    _CoreService_SendReceipt_Handler,
		},
		{
			MethodName: "GetInitialSync",
			Handler:    _CoreService_GetInitialSync_Handler,
		},
		{
			MethodName: "GetSyncDelta",
			Handler:    _CoreService_GetSyncDelta_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventBus",
			Handler:       _CoreService_EventBus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "core.proto",
}
