// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: core.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreService_SendEvent_FullMethodName              = "/core.CoreService/SendEvent"
	CoreService_CreateRoom_FullMethodName             = "/core.CoreService/CreateRoom"
	CoreService_JoinRoom_FullMethodName               = "/core.CoreService/JoinRoom"
	CoreService_LeaveRoom_FullMethodName              = "/core.CoreService/LeaveRoom"
	CoreService_GetMessages_FullMethodName            = "/core.CoreService/GetMessages"
	CoreService_SetPresence_FullMethodName            = "/core.CoreService/SetPresence"
	CoreService_SetTyping_FullMethodName              = "/core.CoreService/SetTyping"
	CoreService_ValidateToken_FullMethodName          = "/core.CoreService/ValidateToken"
	CoreService_GetPendingEvents_FullMethodName       = "/core.CoreService/GetPendingEvents"
	CoreService_EventBus_FullMethodName               = "/core.CoreService/EventBus"
	CoreService_GetMetrics_FullMethodName             = "/core.CoreService/GetMetrics"
	CoreService_GetRoomState_FullMethodName           = "/core.CoreService/GetRoomState"
	CoreService_InviteUser_FullMethodName             = "/core.CoreService/InviteUser"
	CoreService_SetPowerLevels_FullMethodName         = "/core.CoreService/SetPowerLevels"
	CoreService_SendReceipt_FullMethodName            = "/core.CoreService/SendReceipt"
	CoreService_GetInitialSync_FullMethodName         = "/core.CoreService/GetInitialSync"
	CoreService_GetSyncDelta_FullMethodName           = "/core.CoreService/GetSyncDelta"
	CoreService_GetPresence_FullMethodName            = "/core.CoreService/GetPresence"
	CoreService_UpdateProfile_FullMethodName          = "/core.CoreService/UpdateProfile"
	CoreService_WriteAuditLog_FullMethodName          = "/core.CoreService/WriteAuditLog"
	CoreService_DeleteUserKeys_FullMethodName         = "/core.CoreService/DeleteUserKeys"
	CoreService_KickUser_FullMethodName               = "/core.CoreService/KickUser"
	CoreService_BanUser_FullMethodName                = "/core.CoreService/BanUser"
	CoreService_UnbanUser_FullMethodName              = "/core.CoreService/UnbanUser"
	CoreService_ForgetRoom_FullMethodName             = "/core.CoreService/ForgetRoom"
	CoreService_ListPublicRooms_FullMethodName        = "/core.CoreService/ListPublicRooms"
	CoreService_GetEventContext_FullMethodName        = "/core.CoreService/GetEventContext"
	CoreService_InvalidateUserSessions_FullMethodName = "/core.CoreService/InvalidateUserSessions"
	CoreService_UpdateRoomSettings_FullMethodName     = "/core.CoreService/UpdateRoomSettings"
)

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoreService: all gRPC operations between Go Gateway and Elixir Core.
// Go is always the client; Elixir is always the server.
type CoreServiceClient interface {
	// Matrix operations (unary request/response)
	SendEvent(ctx context.Context, in *SendEventRequest, opts ...grpc.CallOption) (*SendEventResponse, error)
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error)
	JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error)
	LeaveRoom(ctx context.Context, in *LeaveRoomRequest, opts ...grpc.CallOption) (*LeaveRoomResponse, error)
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	SetPresence(ctx context.Context, in *SetPresenceRequest, opts ...grpc.CallOption) (*SetPresenceResponse, error)
	SetTyping(ctx context.Context, in *SetTypingRequest, opts ...grpc.CallOption) (*SetTypingResponse, error)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	GetPendingEvents(ctx context.Context, in *GetPendingEventsRequest, opts ...grpc.CallOption) (*GetPendingEventsResponse, error)
	// Event Bus — server-streaming, one stream per Go instance
	EventBus(ctx context.Context, in *EventBusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// GetMetrics — Admin Dashboard live metrics (Epic 3 skeleton; full implementation Epic 4)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	// GetRoomState — unary: Go queries current room members + metadata
	GetRoomState(ctx context.Context, in *GetRoomStateRequest, opts ...grpc.CallOption) (*GetRoomStateResponse, error)
	// InviteUser — invite a user to a room
	InviteUser(ctx context.Context, in *InviteUserRequest, opts ...grpc.CallOption) (*InviteUserResponse, error)
	// SetPowerLevels — update room power levels (caller must have change_state power)
	SetPowerLevels(ctx context.Context, in *SetPowerLevelsRequest, opts ...grpc.CallOption) (*SetPowerLevelsResponse, error)
	// SendReceipt — persists a read receipt for a user in a room
	SendReceipt(ctx context.Context, in *SendReceiptRequest, opts ...grpc.CallOption) (*SendReceiptResponse, error)
	// GetInitialSync — returns full state snapshot for all of a user's joined rooms
	GetInitialSync(ctx context.Context, in *GetInitialSyncRequest, opts ...grpc.CallOption) (*GetInitialSyncResponse, error)
	// GetSyncDelta — incremental sync with long-polling; returns events after since_token
	GetSyncDelta(ctx context.Context, in *GetSyncDeltaRequest, opts ...grpc.CallOption) (*GetSyncDeltaResponse, error)
	// GetPresence — returns presence status for a user (always succeeds; unknown users = offline)
	GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*GetPresenceResponse, error)
	// UpdateProfile — upserts displayname and/or avatar_url for a user
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	// WriteAuditLog — called by Go gateway for admin/compliance events that originate
	// in the Go layer (login, logout, bootstrap). Room events are logged directly by Elixir.
	WriteAuditLog(ctx context.Context, in *WriteAuditLogRequest, opts ...grpc.CallOption) (*WriteAuditLogResponse, error)
	// DeleteUserKeys — DSGVO key deletion: atomically soft-deletes private keys for a user.
	// Story 5.7: instance_admin only. Returns keys_deleted_at (Unix ms) on success.
	// Elixir Core handles the Ecto.Multi + failure-invariant audit emission.
	DeleteUserKeys(ctx context.Context, in *DeleteUserKeysRequest, opts ...grpc.CallOption) (*DeleteUserKeysResponse, error)
	// KickUser — room moderator action; power check enforced by GenServer
	KickUser(ctx context.Context, in *KickUserRequest, opts ...grpc.CallOption) (*KickUserResponse, error)
	// BanUser — bans a user from a room; power check enforced by GenServer
	BanUser(ctx context.Context, in *BanUserRequest, opts ...grpc.CallOption) (*BanUserResponse, error)
	// UnbanUser — removes a ban (sets membership: leave); power check enforced by GenServer
	UnbanUser(ctx context.Context, in *UnbanUserRequest, opts ...grpc.CallOption) (*UnbanUserResponse, error)
	// ForgetRoom — marks a room as excluded from future /sync for the calling user
	ForgetRoom(ctx context.Context, in *ForgetRoomRequest, opts ...grpc.CallOption) (*ForgetRoomResponse, error)
	// ListPublicRooms — returns paginated public rooms (join_rule=public) with live member counts.
	// Story 7-27: GET/POST /_matrix/client/v3/publicRooms.
	ListPublicRooms(ctx context.Context, in *ListPublicRoomsRequest, opts ...grpc.CallOption) (*ListPublicRoomsResponse, error)
	// GetEventContext — returns the target event plus up to `limit` events before
	// and after it, a state snapshot, and pagination tokens compatible with GetMessages.
	// Story 7-28.
	GetEventContext(ctx context.Context, in *GetEventContextRequest, opts ...grpc.CallOption) (*GetEventContextResponse, error)
	// InvalidateUserSessions — Story 6.5: revoke all sessions for a user (admin deactivation).
	// Calls SessionManager.destroy_session/1 for the target user.
	// Returns ok=true on success; gRPC error on DB failure.
	InvalidateUserSessions(ctx context.Context, in *InvalidateUserSessionsRequest, opts ...grpc.CallOption) (*InvalidateUserSessionsResponse, error)
	// UpdateRoomSettings — Story 6.8: Admin API notifies Room GenServer of settings change.
	// max_members = 0 means "no limit". Go gateway sends this after updating rooms table.
	// Elixir Core updates in-memory GenServer state; no-op if GenServer not running (will load from DB on next start).
	UpdateRoomSettings(ctx context.Context, in *UpdateRoomSettingsRequest, opts ...grpc.CallOption) (*UpdateRoomSettingsResponse, error)
}

type coreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServiceClient(cc grpc.ClientConnInterface) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) SendEvent(ctx context.Context, in *SendEventRequest, opts ...grpc.CallOption) (*SendEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEventResponse)
	err := c.cc.Invoke(ctx, CoreService_SendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoomResponse)
	err := c.cc.Invoke(ctx, CoreService_CreateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinRoomResponse)
	err := c.cc.Invoke(ctx, CoreService_JoinRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) LeaveRoom(ctx context.Context, in *LeaveRoomRequest, opts ...grpc.CallOption) (*LeaveRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveRoomResponse)
	err := c.cc.Invoke(ctx, CoreService_LeaveRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, CoreService_GetMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SetPresence(ctx context.Context, in *SetPresenceRequest, opts ...grpc.CallOption) (*SetPresenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPresenceResponse)
	err := c.cc.Invoke(ctx, CoreService_SetPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SetTyping(ctx context.Context, in *SetTypingRequest, opts ...grpc.CallOption) (*SetTypingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTypingResponse)
	err := c.cc.Invoke(ctx, CoreService_SetTyping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, CoreService_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetPendingEvents(ctx context.Context, in *GetPendingEventsRequest, opts ...grpc.CallOption) (*GetPendingEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingEventsResponse)
	err := c.cc.Invoke(ctx, CoreService_GetPendingEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) EventBus(ctx context.Context, in *EventBusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoreService_ServiceDesc.Streams[0], CoreService_EventBus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventBusRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreService_EventBusClient = grpc.ServerStreamingClient[Event]

func (c *coreServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, CoreService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetRoomState(ctx context.Context, in *GetRoomStateRequest, opts ...grpc.CallOption) (*GetRoomStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomStateResponse)
	err := c.cc.Invoke(ctx, CoreService_GetRoomState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) InviteUser(ctx context.Context, in *InviteUserRequest, opts ...grpc.CallOption) (*InviteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteUserResponse)
	err := c.cc.Invoke(ctx, CoreService_InviteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SetPowerLevels(ctx context.Context, in *SetPowerLevelsRequest, opts ...grpc.CallOption) (*SetPowerLevelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPowerLevelsResponse)
	err := c.cc.Invoke(ctx, CoreService_SetPowerLevels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SendReceipt(ctx context.Context, in *SendReceiptRequest, opts ...grpc.CallOption) (*SendReceiptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendReceiptResponse)
	err := c.cc.Invoke(ctx, CoreService_SendReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetInitialSync(ctx context.Context, in *GetInitialSyncRequest, opts ...grpc.CallOption) (*GetInitialSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInitialSyncResponse)
	err := c.cc.Invoke(ctx, CoreService_GetInitialSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetSyncDelta(ctx context.Context, in *GetSyncDeltaRequest, opts ...grpc.CallOption) (*GetSyncDeltaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSyncDeltaResponse)
	err := c.cc.Invoke(ctx, CoreService_GetSyncDelta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*GetPresenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresenceResponse)
	err := c.cc.Invoke(ctx, CoreService_GetPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, CoreService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) WriteAuditLog(ctx context.Context, in *WriteAuditLogRequest, opts ...grpc.CallOption) (*WriteAuditLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteAuditLogResponse)
	err := c.cc.Invoke(ctx, CoreService_WriteAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DeleteUserKeys(ctx context.Context, in *DeleteUserKeysRequest, opts ...grpc.CallOption) (*DeleteUserKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserKeysResponse)
	err := c.cc.Invoke(ctx, CoreService_DeleteUserKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) KickUser(ctx context.Context, in *KickUserRequest, opts ...grpc.CallOption) (*KickUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickUserResponse)
	err := c.cc.Invoke(ctx, CoreService_KickUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) BanUser(ctx context.Context, in *BanUserRequest, opts ...grpc.CallOption) (*BanUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BanUserResponse)
	err := c.cc.Invoke(ctx, CoreService_BanUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) UnbanUser(ctx context.Context, in *UnbanUserRequest, opts ...grpc.CallOption) (*UnbanUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbanUserResponse)
	err := c.cc.Invoke(ctx, CoreService_UnbanUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ForgetRoom(ctx context.Context, in *ForgetRoomRequest, opts ...grpc.CallOption) (*ForgetRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgetRoomResponse)
	err := c.cc.Invoke(ctx, CoreService_ForgetRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ListPublicRooms(ctx context.Context, in *ListPublicRoomsRequest, opts ...grpc.CallOption) (*ListPublicRoomsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublicRoomsResponse)
	err := c.cc.Invoke(ctx, CoreService_ListPublicRooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetEventContext(ctx context.Context, in *GetEventContextRequest, opts ...grpc.CallOption) (*GetEventContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventContextResponse)
	err := c.cc.Invoke(ctx, CoreService_GetEventContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) InvalidateUserSessions(ctx context.Context, in *InvalidateUserSessionsRequest, opts ...grpc.CallOption) (*InvalidateUserSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvalidateUserSessionsResponse)
	err := c.cc.Invoke(ctx, CoreService_InvalidateUserSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) UpdateRoomSettings(ctx context.Context, in *UpdateRoomSettingsRequest, opts ...grpc.CallOption) (*UpdateRoomSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRoomSettingsResponse)
	err := c.cc.Invoke(ctx, CoreService_UpdateRoomSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServiceServer is the server API for CoreService service.
// All implementations must embed UnimplementedCoreServiceServer
// for forward compatibility.
//
// CoreService: all gRPC operations between Go Gateway and Elixir Core.
// Go is always the client; Elixir is always the server.
type CoreServiceServer interface {
	// Matrix operations (unary request/response)
	SendEvent(context.Context, *SendEventRequest) (*SendEventResponse, error)
	CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error)
	JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error)
	LeaveRoom(context.Context, *LeaveRoomRequest) (*LeaveRoomResponse, error)
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	SetPresence(context.Context, *SetPresenceRequest) (*SetPresenceResponse, error)
	SetTyping(context.Context, *SetTypingRequest) (*SetTypingResponse, error)
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	GetPendingEvents(context.Context, *GetPendingEventsRequest) (*GetPendingEventsResponse, error)
	// Event Bus — server-streaming, one stream per Go instance
	EventBus(*EventBusRequest, grpc.ServerStreamingServer[Event]) error
	// GetMetrics — Admin Dashboard live metrics (Epic 3 skeleton; full implementation Epic 4)
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	// GetRoomState — unary: Go queries current room members + metadata
	GetRoomState(context.Context, *GetRoomStateRequest) (*GetRoomStateResponse, error)
	// InviteUser — invite a user to a room
	InviteUser(context.Context, *InviteUserRequest) (*InviteUserResponse, error)
	// SetPowerLevels — update room power levels (caller must have change_state power)
	SetPowerLevels(context.Context, *SetPowerLevelsRequest) (*SetPowerLevelsResponse, error)
	// SendReceipt — persists a read receipt for a user in a room
	SendReceipt(context.Context, *SendReceiptRequest) (*SendReceiptResponse, error)
	// GetInitialSync — returns full state snapshot for all of a user's joined rooms
	GetInitialSync(context.Context, *GetInitialSyncRequest) (*GetInitialSyncResponse, error)
	// GetSyncDelta — incremental sync with long-polling; returns events after since_token
	GetSyncDelta(context.Context, *GetSyncDeltaRequest) (*GetSyncDeltaResponse, error)
	// GetPresence — returns presence status for a user (always succeeds; unknown users = offline)
	GetPresence(context.Context, *GetPresenceRequest) (*GetPresenceResponse, error)
	// UpdateProfile — upserts displayname and/or avatar_url for a user
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	// WriteAuditLog — called by Go gateway for admin/compliance events that originate
	// in the Go layer (login, logout, bootstrap). Room events are logged directly by Elixir.
	WriteAuditLog(context.Context, *WriteAuditLogRequest) (*WriteAuditLogResponse, error)
	// DeleteUserKeys — DSGVO key deletion: atomically soft-deletes private keys for a user.
	// Story 5.7: instance_admin only. Returns keys_deleted_at (Unix ms) on success.
	// Elixir Core handles the Ecto.Multi + failure-invariant audit emission.
	DeleteUserKeys(context.Context, *DeleteUserKeysRequest) (*DeleteUserKeysResponse, error)
	// KickUser — room moderator action; power check enforced by GenServer
	KickUser(context.Context, *KickUserRequest) (*KickUserResponse, error)
	// BanUser — bans a user from a room; power check enforced by GenServer
	BanUser(context.Context, *BanUserRequest) (*BanUserResponse, error)
	// UnbanUser — removes a ban (sets membership: leave); power check enforced by GenServer
	UnbanUser(context.Context, *UnbanUserRequest) (*UnbanUserResponse, error)
	// ForgetRoom — marks a room as excluded from future /sync for the calling user
	ForgetRoom(context.Context, *ForgetRoomRequest) (*ForgetRoomResponse, error)
	// ListPublicRooms — returns paginated public rooms (join_rule=public) with live member counts.
	// Story 7-27: GET/POST /_matrix/client/v3/publicRooms.
	ListPublicRooms(context.Context, *ListPublicRoomsRequest) (*ListPublicRoomsResponse, error)
	// GetEventContext — returns the target event plus up to `limit` events before
	// and after it, a state snapshot, and pagination tokens compatible with GetMessages.
	// Story 7-28.
	GetEventContext(context.Context, *GetEventContextRequest) (*GetEventContextResponse, error)
	// InvalidateUserSessions — Story 6.5: revoke all sessions for a user (admin deactivation).
	// Calls SessionManager.destroy_session/1 for the target user.
	// Returns ok=true on success; gRPC error on DB failure.
	InvalidateUserSessions(context.Context, *InvalidateUserSessionsRequest) (*InvalidateUserSessionsResponse, error)
	// UpdateRoomSettings — Story 6.8: Admin API notifies Room GenServer of settings change.
	// max_members = 0 means "no limit". Go gateway sends this after updating rooms table.
	// Elixir Core updates in-memory GenServer state; no-op if GenServer not running (will load from DB on next start).
	UpdateRoomSettings(context.Context, *UpdateRoomSettingsRequest) (*UpdateRoomSettingsResponse, error)
	mustEmbedUnimplementedCoreServiceServer()
}

// UnimplementedCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServiceServer struct{}

func (UnimplementedCoreServiceServer) SendEvent(context.Context, *SendEventRequest) (*SendEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedCoreServiceServer) CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRoom not implemented")
}
func (UnimplementedCoreServiceServer) JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinRoom not implemented")
}
func (UnimplementedCoreServiceServer) LeaveRoom(context.Context, *LeaveRoomRequest) (*LeaveRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveRoom not implemented")
}
func (UnimplementedCoreServiceServer) GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedCoreServiceServer) SetPresence(context.Context, *SetPresenceRequest) (*SetPresenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPresence not implemented")
}
func (UnimplementedCoreServiceServer) SetTyping(context.Context, *SetTypingRequest) (*SetTypingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTyping not implemented")
}
func (UnimplementedCoreServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedCoreServiceServer) GetPendingEvents(context.Context, *GetPendingEventsRequest) (*GetPendingEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingEvents not implemented")
}
func (UnimplementedCoreServiceServer) EventBus(*EventBusRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method EventBus not implemented")
}
func (UnimplementedCoreServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedCoreServiceServer) GetRoomState(context.Context, *GetRoomStateRequest) (*GetRoomStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoomState not implemented")
}
func (UnimplementedCoreServiceServer) InviteUser(context.Context, *InviteUserRequest) (*InviteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteUser not implemented")
}
func (UnimplementedCoreServiceServer) SetPowerLevels(context.Context, *SetPowerLevelsRequest) (*SetPowerLevelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPowerLevels not implemented")
}
func (UnimplementedCoreServiceServer) SendReceipt(context.Context, *SendReceiptRequest) (*SendReceiptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendReceipt not implemented")
}
func (UnimplementedCoreServiceServer) GetInitialSync(context.Context, *GetInitialSyncRequest) (*GetInitialSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInitialSync not implemented")
}
func (UnimplementedCoreServiceServer) GetSyncDelta(context.Context, *GetSyncDeltaRequest) (*GetSyncDeltaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncDelta not implemented")
}
func (UnimplementedCoreServiceServer) GetPresence(context.Context, *GetPresenceRequest) (*GetPresenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPresence not implemented")
}
func (UnimplementedCoreServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedCoreServiceServer) WriteAuditLog(context.Context, *WriteAuditLogRequest) (*WriteAuditLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteAuditLog not implemented")
}
func (UnimplementedCoreServiceServer) DeleteUserKeys(context.Context, *DeleteUserKeysRequest) (*DeleteUserKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserKeys not implemented")
}
func (UnimplementedCoreServiceServer) KickUser(context.Context, *KickUserRequest) (*KickUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KickUser not implemented")
}
func (UnimplementedCoreServiceServer) BanUser(context.Context, *BanUserRequest) (*BanUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BanUser not implemented")
}
func (UnimplementedCoreServiceServer) UnbanUser(context.Context, *UnbanUserRequest) (*UnbanUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbanUser not implemented")
}
func (UnimplementedCoreServiceServer) ForgetRoom(context.Context, *ForgetRoomRequest) (*ForgetRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForgetRoom not implemented")
}
func (UnimplementedCoreServiceServer) ListPublicRooms(context.Context, *ListPublicRoomsRequest) (*ListPublicRoomsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPublicRooms not implemented")
}
func (UnimplementedCoreServiceServer) GetEventContext(context.Context, *GetEventContextRequest) (*GetEventContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventContext not implemented")
}
func (UnimplementedCoreServiceServer) InvalidateUserSessions(context.Context, *InvalidateUserSessionsRequest) (*InvalidateUserSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvalidateUserSessions not implemented")
}
func (UnimplementedCoreServiceServer) UpdateRoomSettings(context.Context, *UpdateRoomSettingsRequest) (*UpdateRoomSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRoomSettings not implemented")
}
func (UnimplementedCoreServiceServer) mustEmbedUnimplementedCoreServiceServer() {}
func (UnimplementedCoreServiceServer) testEmbeddedByValue()                     {}

// UnsafeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServiceServer will
// result in compilation errors.
type UnsafeCoreServiceServer interface {
	mustEmbedUnimplementedCoreServiceServer()
}

func RegisterCoreServiceServer(s grpc.ServiceRegistrar, srv CoreServiceServer) {
	// If the following call panics, it indicates UnimplementedCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreService_ServiceDesc, srv)
}

func _CoreService_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_SendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SendEvent(ctx, req.(*SendEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_CreateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_JoinRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).JoinRoom(ctx, req.(*JoinRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_LeaveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).LeaveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_LeaveRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).LeaveRoom(ctx, req.(*LeaveRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SetPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SetPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_SetPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SetPresence(ctx, req.(*SetPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SetTyping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTypingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SetTyping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_SetTyping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SetTyping(ctx, req.(*SetTypingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetPendingEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetPendingEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetPendingEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetPendingEvents(ctx, req.(*GetPendingEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_EventBus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventBusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServiceServer).EventBus(m, &grpc.GenericServerStream[EventBusRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreService_EventBusServer = grpc.ServerStreamingServer[Event]

func _CoreService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetRoomState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetRoomState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetRoomState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetRoomState(ctx, req.(*GetRoomStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_InviteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).InviteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_InviteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).InviteUser(ctx, req.(*InviteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SetPowerLevels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPowerLevelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SetPowerLevels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_SetPowerLevels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SetPowerLevels(ctx, req.(*SetPowerLevelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SendReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SendReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_SendReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SendReceipt(ctx, req.(*SendReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetInitialSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInitialSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetInitialSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetInitialSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetInitialSync(ctx, req.(*GetInitialSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetSyncDelta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyncDeltaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetSyncDelta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetSyncDelta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetSyncDelta(ctx, req.(*GetSyncDeltaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetPresence(ctx, req.(*GetPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_WriteAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).WriteAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_WriteAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).WriteAuditLog(ctx, req.(*WriteAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DeleteUserKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DeleteUserKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_DeleteUserKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DeleteUserKeys(ctx, req.(*DeleteUserKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_KickUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).KickUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_KickUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).KickUser(ctx, req.(*KickUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_BanUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).BanUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_BanUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).BanUser(ctx, req.(*BanUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_UnbanUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbanUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).UnbanUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_UnbanUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).UnbanUser(ctx, req.(*UnbanUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ForgetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ForgetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ForgetRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ForgetRoom(ctx, req.(*ForgetRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ListPublicRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublicRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ListPublicRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ListPublicRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ListPublicRooms(ctx, req.(*ListPublicRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetEventContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetEventContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetEventContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetEventContext(ctx, req.(*GetEventContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_InvalidateUserSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateUserSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).InvalidateUserSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_InvalidateUserSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).InvalidateUserSessions(ctx, req.(*InvalidateUserSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_UpdateRoomSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoomSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).UpdateRoomSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_UpdateRoomSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).UpdateRoomSettings(ctx, req.(*UpdateRoomSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreService_ServiceDesc is the grpc.ServiceDesc for CoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEvent",
			Handler:    _CoreService_SendEvent_Handler,
		},
		{
			MethodName: "CreateRoom",
			Handler:    _CoreService_CreateRoom_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _CoreService_JoinRoom_Handler,
		},
		{
			MethodName: "LeaveRoom",
			Handler:    _CoreService_LeaveRoom_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _CoreService_GetMessages_Handler,
		},
		{
			MethodName: "SetPresence",
			Handler:    _CoreService_SetPresence_Handler,
		},
		{
			MethodName: "SetTyping",
			Handler:    _CoreService_SetTyping_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _CoreService_ValidateToken_Handler,
		},
		{
			MethodName: "GetPendingEvents",
			Handler:    _CoreService_GetPendingEvents_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _CoreService_GetMetrics_Handler,
		},
		{
			MethodName: "GetRoomState",
			Handler:    _CoreService_GetRoomState_Handler,
		},
		{
			MethodName: "InviteUser",
			Handler:    _CoreService_InviteUser_Handler,
		},
		{
			MethodName: "SetPowerLevels",
			Handler:    _CoreService_SetPowerLevels_Handler,
		},
		{
			MethodName: "SendReceipt",
			Handler:    _CoreService_SendReceipt_Handler,
		},
		{
			MethodName: "GetInitialSync",
			Handler:    _CoreService_GetInitialSync_Handler,
		},
		{
			MethodName: "GetSyncDelta",
			Handler:    _CoreService_GetSyncDelta_Handler,
		},
		{
			MethodName: "GetPresence",
			Handler:    _CoreService_GetPresence_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _CoreService_UpdateProfile_Handler,
		},
		{
			MethodName: "WriteAuditLog",
			Handler:    _CoreService_WriteAuditLog_Handler,
		},
		{
			MethodName: "DeleteUserKeys",
			Handler:    _CoreService_DeleteUserKeys_Handler,
		},
		{
			MethodName: "KickUser",
			Handler:    _CoreService_KickUser_Handler,
		},
		{
			MethodName: "BanUser",
			Handler:    _CoreService_BanUser_Handler,
		},
		{
			MethodName: "UnbanUser",
			Handler:    _CoreService_UnbanUser_Handler,
		},
		{
			MethodName: "ForgetRoom",
			Handler:    _CoreService_ForgetRoom_Handler,
		},
		{
			MethodName: "ListPublicRooms",
			Handler:    _CoreService_ListPublicRooms_Handler,
		},
		{
			MethodName: "GetEventContext",
			Handler:    _CoreService_GetEventContext_Handler,
		},
		{
			MethodName: "InvalidateUserSessions",
			Handler:    _CoreService_InvalidateUserSessions_Handler,
		},
		{
			MethodName: "UpdateRoomSettings",
			Handler:    _CoreService_UpdateRoomSettings_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventBus",
			Handler:       _CoreService_EventBus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "core.proto",
}
