// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shared event type used across multiple RPCs
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                    // JSON-encoded event content
	OriginTs      int64                  `protobuf:"varint,6,opt,name=origin_ts,json=originTs,proto3" json:"origin_ts,omitempty"` // Unix milliseconds
	ServerTs      int64                  `protobuf:"varint,7,opt,name=server_ts,json=serverTs,proto3" json:"server_ts,omitempty"` // Unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Event) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Event) GetOriginTs() int64 {
	if x != nil {
		return x.OriginTs
	}
	return 0
}

func (x *Event) GetServerTs() int64 {
	if x != nil {
		return x.ServerTs
	}
	return 0
}

// SendEvent
type SendEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	TxnId         string                 `protobuf:"bytes,4,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"` // idempotency key
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	OriginTs      int64                  `protobuf:"varint,6,opt,name=origin_ts,json=originTs,proto3" json:"origin_ts,omitempty"` // Unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEventRequest) Reset() {
	*x = SendEventRequest{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEventRequest) ProtoMessage() {}

func (x *SendEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEventRequest.ProtoReflect.Descriptor instead.
func (*SendEventRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *SendEventRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendEventRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SendEventRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *SendEventRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SendEventRequest) GetOriginTs() int64 {
	if x != nil {
		return x.OriginTs
	}
	return 0
}

type SendEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEventResponse) Reset() {
	*x = SendEventResponse{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEventResponse) ProtoMessage() {}

func (x *SendEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEventResponse.ProtoReflect.Descriptor instead.
func (*SendEventResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *SendEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// CreateRoom
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     string                 `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Topic         *string                `protobuf:"bytes,3,opt,name=topic,proto3,oneof" json:"topic,omitempty"`
	IsDirect      bool                   `protobuf:"varint,4,opt,name=is_direct,json=isDirect,proto3" json:"is_direct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateRoomRequest) GetTopic() string {
	if x != nil && x.Topic != nil {
		return *x.Topic
	}
	return ""
}

func (x *CreateRoomRequest) GetIsDirect() bool {
	if x != nil {
		return x.IsDirect
	}
	return false
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// JoinRoom
type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomIdOrAlias string                 `protobuf:"bytes,2,opt,name=room_id_or_alias,json=roomIdOrAlias,proto3" json:"room_id_or_alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinRoomRequest) GetRoomIdOrAlias() string {
	if x != nil {
		return x.RoomIdOrAlias
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{6}
}

func (x *JoinRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// GetMessages
type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	FromToken     string                 `protobuf:"bytes,2,opt,name=from_token,json=fromToken,proto3" json:"from_token,omitempty"`
	ToToken       *string                `protobuf:"bytes,3,opt,name=to_token,json=toToken,proto3,oneof" json:"to_token,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Direction     string                 `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"` // "b" (backward) or "f" (forward)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{7}
}

func (x *GetMessagesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetMessagesRequest) GetFromToken() string {
	if x != nil {
		return x.FromToken
	}
	return ""
}

func (x *GetMessagesRequest) GetToToken() string {
	if x != nil && x.ToToken != nil {
		return *x.ToToken
	}
	return ""
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMessagesRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextBatch     string                 `protobuf:"bytes,2,opt,name=next_batch,json=nextBatch,proto3" json:"next_batch,omitempty"`
	PrevBatch     string                 `protobuf:"bytes,3,opt,name=prev_batch,json=prevBatch,proto3" json:"prev_batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessagesResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetMessagesResponse) GetNextBatch() string {
	if x != nil {
		return x.NextBatch
	}
	return ""
}

func (x *GetMessagesResponse) GetPrevBatch() string {
	if x != nil {
		return x.PrevBatch
	}
	return ""
}

// SetPresence
type SetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Presence      string                 `protobuf:"bytes,2,opt,name=presence,proto3" json:"presence,omitempty"` // "online", "offline", "unavailable"
	StatusMsg     *string                `protobuf:"bytes,3,opt,name=status_msg,json=statusMsg,proto3,oneof" json:"status_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPresenceRequest) Reset() {
	*x = SetPresenceRequest{}
	mi := &file_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPresenceRequest) ProtoMessage() {}

func (x *SetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPresenceRequest.ProtoReflect.Descriptor instead.
func (*SetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{9}
}

func (x *SetPresenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetPresenceRequest) GetPresence() string {
	if x != nil {
		return x.Presence
	}
	return ""
}

func (x *SetPresenceRequest) GetStatusMsg() string {
	if x != nil && x.StatusMsg != nil {
		return *x.StatusMsg
	}
	return ""
}

type SetPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPresenceResponse) Reset() {
	*x = SetPresenceResponse{}
	mi := &file_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPresenceResponse) ProtoMessage() {}

func (x *SetPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPresenceResponse.ProtoReflect.Descriptor instead.
func (*SetPresenceResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{10}
}

// SetTyping
type SetTypingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Typing        bool                   `protobuf:"varint,3,opt,name=typing,proto3" json:"typing,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTypingRequest) Reset() {
	*x = SetTypingRequest{}
	mi := &file_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTypingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTypingRequest) ProtoMessage() {}

func (x *SetTypingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTypingRequest.ProtoReflect.Descriptor instead.
func (*SetTypingRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{11}
}

func (x *SetTypingRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SetTypingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetTypingRequest) GetTyping() bool {
	if x != nil {
		return x.Typing
	}
	return false
}

func (x *SetTypingRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type SetTypingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTypingResponse) Reset() {
	*x = SetTypingResponse{}
	mi := &file_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTypingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTypingResponse) ProtoMessage() {}

func (x *SetTypingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTypingResponse.ProtoReflect.Descriptor instead.
func (*SetTypingResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{12}
}

// ValidateToken — Go validates OIDC token, Elixir trusts Go fully (ADR G2)
// user_id and system_role arrive via gRPC metadata (x-user-id, x-system-role).
// display_name and email are for new-user provisioning only.
type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // OIDC preferred_username claim (Operational PII, Tier 1)
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`                                // OIDC email claim (Sensitive PII, Tier 2)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{13}
}

func (x *ValidateTokenRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ValidateTokenRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // @{sub}:{server_name}
	SystemRole    string                 `protobuf:"bytes,3,opt,name=system_role,json=systemRole,proto3" json:"system_role,omitempty"`    // "user" | "instance_admin" | "compliance_officer"
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // Decrypted from Operational PII (Tier 1)
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`         // User account status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{14}
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetSystemRole() string {
	if x != nil {
		return x.SystemRole
	}
	return ""
}

func (x *ValidateTokenResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ValidateTokenResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// GetPendingEvents — GELB-status fallback (unary polling instead of streaming)
type GetPendingEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SinceToken    string                 `protobuf:"bytes,2,opt,name=since_token,json=sinceToken,proto3" json:"since_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingEventsRequest) Reset() {
	*x = GetPendingEventsRequest{}
	mi := &file_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingEventsRequest) ProtoMessage() {}

func (x *GetPendingEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingEventsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingEventsRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{15}
}

func (x *GetPendingEventsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetPendingEventsRequest) GetSinceToken() string {
	if x != nil {
		return x.SinceToken
	}
	return ""
}

type GetPendingEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextToken     string                 `protobuf:"bytes,2,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingEventsResponse) Reset() {
	*x = GetPendingEventsResponse{}
	mi := &file_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingEventsResponse) ProtoMessage() {}

func (x *GetPendingEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingEventsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingEventsResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{16}
}

func (x *GetPendingEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetPendingEventsResponse) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

// EventBus — server-streaming, one stream per Go gateway instance
type EventBusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SinceToken    *string                `protobuf:"bytes,2,opt,name=since_token,json=sinceToken,proto3,oneof" json:"since_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBusRequest) Reset() {
	*x = EventBusRequest{}
	mi := &file_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBusRequest) ProtoMessage() {}

func (x *EventBusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBusRequest.ProtoReflect.Descriptor instead.
func (*EventBusRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{17}
}

func (x *EventBusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EventBusRequest) GetSinceToken() string {
	if x != nil && x.SinceToken != nil {
		return *x.SinceToken
	}
	return ""
}

// GetMetrics — Admin Dashboard live metrics (Epic 3 skeleton; full implementation Epic 4)
type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{18}
}

type GetMetricsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgPerSec      float32                `protobuf:"fixed32,1,opt,name=msg_per_sec,json=msgPerSec,proto3" json:"msg_per_sec,omitempty"`             // messages per second (rolling 60s window)
	ActiveSessions int32                  `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"` // currently active user sessions
	RoomCount      int32                  `protobuf:"varint,3,opt,name=room_count,json=roomCount,proto3" json:"room_count,omitempty"`                // total number of active rooms
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{19}
}

func (x *GetMetricsResponse) GetMsgPerSec() float32 {
	if x != nil {
		return x.MsgPerSec
	}
	return 0
}

func (x *GetMetricsResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *GetMetricsResponse) GetRoomCount() int32 {
	if x != nil {
		return x.RoomCount
	}
	return 0
}

// InviteUser
type InviteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	InviterId     string                 `protobuf:"bytes,2,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"` // caller (must be room member)
	InviteeId     string                 `protobuf:"bytes,3,opt,name=invitee_id,json=inviteeId,proto3" json:"invitee_id,omitempty"` // user to invite
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteUserRequest) Reset() {
	*x = InviteUserRequest{}
	mi := &file_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserRequest) ProtoMessage() {}

func (x *InviteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserRequest.ProtoReflect.Descriptor instead.
func (*InviteUserRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{20}
}

func (x *InviteUserRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *InviteUserRequest) GetInviterId() string {
	if x != nil {
		return x.InviterId
	}
	return ""
}

func (x *InviteUserRequest) GetInviteeId() string {
	if x != nil {
		return x.InviteeId
	}
	return ""
}

type InviteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteUserResponse) Reset() {
	*x = InviteUserResponse{}
	mi := &file_core_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserResponse) ProtoMessage() {}

func (x *InviteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserResponse.ProtoReflect.Descriptor instead.
func (*InviteUserResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{21}
}

// GetRoomState — unary: Go queries current room members + metadata
type GetRoomStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomStateRequest) Reset() {
	*x = GetRoomStateRequest{}
	mi := &file_core_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomStateRequest) ProtoMessage() {}

func (x *GetRoomStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomStateRequest.ProtoReflect.Descriptor instead.
func (*GetRoomStateRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{22}
}

func (x *GetRoomStateRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomStateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Members         []string               `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	PowerLevelsJson string                 `protobuf:"bytes,2,opt,name=power_levels_json,json=powerLevelsJson,proto3" json:"power_levels_json,omitempty"` // JSON string — full power levels in Story 4-13
	RoomName        string                 `protobuf:"bytes,3,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`                        // empty for now — full room metadata in Story 4-9
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRoomStateResponse) Reset() {
	*x = GetRoomStateResponse{}
	mi := &file_core_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomStateResponse) ProtoMessage() {}

func (x *GetRoomStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomStateResponse.ProtoReflect.Descriptor instead.
func (*GetRoomStateResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{23}
}

func (x *GetRoomStateResponse) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GetRoomStateResponse) GetPowerLevelsJson() string {
	if x != nil {
		return x.PowerLevelsJson
	}
	return ""
}

func (x *GetRoomStateResponse) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

// SetPowerLevels — update room power levels (caller must have change_state power)
type SetPowerLevelsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PowerLevelsJson string                 `protobuf:"bytes,2,opt,name=power_levels_json,json=powerLevelsJson,proto3" json:"power_levels_json,omitempty"` // JSON string of full power_levels map
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetPowerLevelsRequest) Reset() {
	*x = SetPowerLevelsRequest{}
	mi := &file_core_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPowerLevelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPowerLevelsRequest) ProtoMessage() {}

func (x *SetPowerLevelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPowerLevelsRequest.ProtoReflect.Descriptor instead.
func (*SetPowerLevelsRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{24}
}

func (x *SetPowerLevelsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SetPowerLevelsRequest) GetPowerLevelsJson() string {
	if x != nil {
		return x.PowerLevelsJson
	}
	return ""
}

type SetPowerLevelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPowerLevelsResponse) Reset() {
	*x = SetPowerLevelsResponse{}
	mi := &file_core_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPowerLevelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPowerLevelsResponse) ProtoMessage() {}

func (x *SetPowerLevelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPowerLevelsResponse.ProtoReflect.Descriptor instead.
func (*SetPowerLevelsResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{25}
}

// GetInitialSync — returns full state snapshot for all of a user's joined rooms
type GetInitialSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInitialSyncRequest) Reset() {
	*x = GetInitialSyncRequest{}
	mi := &file_core_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInitialSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInitialSyncRequest) ProtoMessage() {}

func (x *GetInitialSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInitialSyncRequest.ProtoReflect.Descriptor instead.
func (*GetInitialSyncRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{26}
}

func (x *GetInitialSyncRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetInitialSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceToken    string                 `protobuf:"bytes,1,opt,name=since_token,json=sinceToken,proto3" json:"since_token,omitempty"` // opaque token — becomes next_batch in HTTP response
	Rooms         []*SyncRoom            `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInitialSyncResponse) Reset() {
	*x = GetInitialSyncResponse{}
	mi := &file_core_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInitialSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInitialSyncResponse) ProtoMessage() {}

func (x *GetInitialSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInitialSyncResponse.ProtoReflect.Descriptor instead.
func (*GetInitialSyncResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{27}
}

func (x *GetInitialSyncResponse) GetSinceToken() string {
	if x != nil {
		return x.SinceToken
	}
	return ""
}

func (x *GetInitialSyncResponse) GetRooms() []*SyncRoom {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// SyncRoomStateEvent represents a state event in a SyncRoom (needs state_key)
type SyncRoomStateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // e.g. "m.room.member", "m.room.power_levels"
	StateKey      string                 `protobuf:"bytes,2,opt,name=state_key,json=stateKey,proto3" json:"state_key,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // JSON-encoded content
	Sender        string                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRoomStateEvent) Reset() {
	*x = SyncRoomStateEvent{}
	mi := &file_core_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRoomStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRoomStateEvent) ProtoMessage() {}

func (x *SyncRoomStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRoomStateEvent.ProtoReflect.Descriptor instead.
func (*SyncRoomStateEvent) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{28}
}

func (x *SyncRoomStateEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SyncRoomStateEvent) GetStateKey() string {
	if x != nil {
		return x.StateKey
	}
	return ""
}

func (x *SyncRoomStateEvent) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SyncRoomStateEvent) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

// GetSyncDelta — incremental sync request with long-polling
type GetSyncDeltaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SinceToken    string                 `protobuf:"bytes,2,opt,name=since_token,json=sinceToken,proto3" json:"since_token,omitempty"` // opaque token from previous next_batch
	TimeoutMs     int64                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`   // long-poll wait time; 0 = return immediately; max 30000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncDeltaRequest) Reset() {
	*x = GetSyncDeltaRequest{}
	mi := &file_core_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncDeltaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncDeltaRequest) ProtoMessage() {}

func (x *GetSyncDeltaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncDeltaRequest.ProtoReflect.Descriptor instead.
func (*GetSyncDeltaRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{29}
}

func (x *GetSyncDeltaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSyncDeltaRequest) GetSinceToken() string {
	if x != nil {
		return x.SinceToken
	}
	return ""
}

func (x *GetSyncDeltaRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type GetSyncDeltaResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SinceToken        string                 `protobuf:"bytes,1,opt,name=since_token,json=sinceToken,proto3" json:"since_token,omitempty"`                         // new next_batch token for the client
	Rooms             []*SyncRoom            `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms,omitempty"`                                                     // only rooms with new events
	FallbackToInitial bool                   `protobuf:"varint,3,opt,name=fallback_to_initial,json=fallbackToInitial,proto3" json:"fallback_to_initial,omitempty"` // true if since_token was unknown → full sync
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSyncDeltaResponse) Reset() {
	*x = GetSyncDeltaResponse{}
	mi := &file_core_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncDeltaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncDeltaResponse) ProtoMessage() {}

func (x *GetSyncDeltaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncDeltaResponse.ProtoReflect.Descriptor instead.
func (*GetSyncDeltaResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{30}
}

func (x *GetSyncDeltaResponse) GetSinceToken() string {
	if x != nil {
		return x.SinceToken
	}
	return ""
}

func (x *GetSyncDeltaResponse) GetRooms() []*SyncRoom {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *GetSyncDeltaResponse) GetFallbackToInitial() bool {
	if x != nil {
		return x.FallbackToInitial
	}
	return false
}

// SyncRoom represents one joined room's state in an initial sync
type SyncRoom struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	StateEvents    []*SyncRoomStateEvent  `protobuf:"bytes,2,rep,name=state_events,json=stateEvents,proto3" json:"state_events,omitempty"`
	TimelineEvents []*Event               `protobuf:"bytes,3,rep,name=timeline_events,json=timelineEvents,proto3" json:"timeline_events,omitempty"`
	Limited        bool                   `protobuf:"varint,4,opt,name=limited,proto3" json:"limited,omitempty"`                     // true if timeline was truncated at 20
	PrevBatch      string                 `protobuf:"bytes,5,opt,name=prev_batch,json=prevBatch,proto3" json:"prev_batch,omitempty"` // pagination token for GET /messages
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncRoom) Reset() {
	*x = SyncRoom{}
	mi := &file_core_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRoom) ProtoMessage() {}

func (x *SyncRoom) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRoom.ProtoReflect.Descriptor instead.
func (*SyncRoom) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{31}
}

func (x *SyncRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SyncRoom) GetStateEvents() []*SyncRoomStateEvent {
	if x != nil {
		return x.StateEvents
	}
	return nil
}

func (x *SyncRoom) GetTimelineEvents() []*Event {
	if x != nil {
		return x.TimelineEvents
	}
	return nil
}

func (x *SyncRoom) GetLimited() bool {
	if x != nil {
		return x.Limited
	}
	return false
}

func (x *SyncRoom) GetPrevBatch() string {
	if x != nil {
		return x.PrevBatch
	}
	return ""
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x04core\"\xcb\x01\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x12\x1b\n" +
	"\torigin_ts\x18\x06 \x01(\x03R\boriginTs\x12\x1b\n" +
	"\tserver_ts\x18\a \x01(\x03R\bserverTs\"\xb5\x01\n" +
	"\x10SendEventRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x15\n" +
	"\x06txn_id\x18\x04 \x01(\tR\x05txnId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x12\x1b\n" +
	"\torigin_ts\x18\x06 \x01(\x03R\boriginTs\".\n" +
	"\x11SendEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"\x96\x01\n" +
	"\x11CreateRoomRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\tR\tcreatorId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05topic\x18\x03 \x01(\tH\x01R\x05topic\x88\x01\x01\x12\x1b\n" +
	"\tis_direct\x18\x04 \x01(\bR\bisDirectB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_topic\"-\n" +
	"\x12CreateRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"S\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x10room_id_or_alias\x18\x02 \x01(\tR\rroomIdOrAlias\"+\n" +
	"\x10JoinRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\xad\x01\n" +
	"\x12GetMessagesRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"from_token\x18\x02 \x01(\tR\tfromToken\x12\x1e\n" +
	"\bto_token\x18\x03 \x01(\tH\x00R\atoToken\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\tR\tdirectionB\v\n" +
	"\t_to_token\"x\n" +
	"\x13GetMessagesResponse\x12#\n" +
	"\x06events\x18\x01 \x03(\v2\v.core.EventR\x06events\x12\x1d\n" +
	"\n" +
	"next_batch\x18\x02 \x01(\tR\tnextBatch\x12\x1d\n" +
	"\n" +
	"prev_batch\x18\x03 \x01(\tR\tprevBatch\"|\n" +
	"\x12SetPresenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpresence\x18\x02 \x01(\tR\bpresence\x12\"\n" +
	"\n" +
	"status_msg\x18\x03 \x01(\tH\x00R\tstatusMsg\x88\x01\x01B\r\n" +
	"\v_status_msg\"\x15\n" +
	"\x13SetPresenceResponse\"{\n" +
	"\x10SetTypingRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06typing\x18\x03 \x01(\bR\x06typing\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\"\x13\n" +
	"\x11SetTypingResponse\"U\n" +
	"\x14ValidateTokenRequest\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05emailJ\x04\b\x01\x10\x02\"\x97\x01\n" +
	"\x15ValidateTokenResponse\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vsystem_role\x18\x03 \x01(\tR\n" +
	"systemRole\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActiveJ\x04\b\x01\x10\x02\"S\n" +
	"\x17GetPendingEventsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vsince_token\x18\x02 \x01(\tR\n" +
	"sinceToken\"^\n" +
	"\x18GetPendingEventsResponse\x12#\n" +
	"\x06events\x18\x01 \x03(\v2\v.core.EventR\x06events\x12\x1d\n" +
	"\n" +
	"next_token\x18\x02 \x01(\tR\tnextToken\"`\n" +
	"\x0fEventBusRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12$\n" +
	"\vsince_token\x18\x02 \x01(\tH\x00R\n" +
	"sinceToken\x88\x01\x01B\x0e\n" +
	"\f_since_token\"\x13\n" +
	"\x11GetMetricsRequest\"|\n" +
	"\x12GetMetricsResponse\x12\x1e\n" +
	"\vmsg_per_sec\x18\x01 \x01(\x02R\tmsgPerSec\x12'\n" +
	"\x0factive_sessions\x18\x02 \x01(\x05R\x0eactiveSessions\x12\x1d\n" +
	"\n" +
	"room_count\x18\x03 \x01(\x05R\troomCount\"j\n" +
	"\x11InviteUserRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"inviter_id\x18\x02 \x01(\tR\tinviterId\x12\x1d\n" +
	"\n" +
	"invitee_id\x18\x03 \x01(\tR\tinviteeId\"\x14\n" +
	"\x12InviteUserResponse\".\n" +
	"\x13GetRoomStateRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"y\n" +
	"\x14GetRoomStateResponse\x12\x18\n" +
	"\amembers\x18\x01 \x03(\tR\amembers\x12*\n" +
	"\x11power_levels_json\x18\x02 \x01(\tR\x0fpowerLevelsJson\x12\x1b\n" +
	"\troom_name\x18\x03 \x01(\tR\broomName\"\\\n" +
	"\x15SetPowerLevelsRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12*\n" +
	"\x11power_levels_json\x18\x02 \x01(\tR\x0fpowerLevelsJson\"\x18\n" +
	"\x16SetPowerLevelsResponse\"0\n" +
	"\x15GetInitialSyncRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"_\n" +
	"\x16GetInitialSyncResponse\x12\x1f\n" +
	"\vsince_token\x18\x01 \x01(\tR\n" +
	"sinceToken\x12$\n" +
	"\x05rooms\x18\x02 \x03(\v2\x0e.core.SyncRoomR\x05rooms\"w\n" +
	"\x12SyncRoomStateEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tstate_key\x18\x02 \x01(\tR\bstateKey\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\tR\x06sender\"n\n" +
	"\x13GetSyncDeltaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vsince_token\x18\x02 \x01(\tR\n" +
	"sinceToken\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\"\x8d\x01\n" +
	"\x14GetSyncDeltaResponse\x12\x1f\n" +
	"\vsince_token\x18\x01 \x01(\tR\n" +
	"sinceToken\x12$\n" +
	"\x05rooms\x18\x02 \x03(\v2\x0e.core.SyncRoomR\x05rooms\x12.\n" +
	"\x13fallback_to_initial\x18\x03 \x01(\bR\x11fallbackToInitial\"\xcf\x01\n" +
	"\bSyncRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12;\n" +
	"\fstate_events\x18\x02 \x03(\v2\x18.core.SyncRoomStateEventR\vstateEvents\x124\n" +
	"\x0ftimeline_events\x18\x03 \x03(\v2\v.core.EventR\x0etimelineEvents\x12\x18\n" +
	"\alimited\x18\x04 \x01(\bR\alimited\x12\x1d\n" +
	"\n" +
	"prev_batch\x18\x05 \x01(\tR\tprevBatch2\x86\b\n" +
	"\vCoreService\x12<\n" +
	"\tSendEvent\x12\x16.core.SendEventRequest\x1a\x17.core.SendEventResponse\x12?\n" +
	"\n" +
	"CreateRoom\x12\x17.core.CreateRoomRequest\x1a\x18.core.CreateRoomResponse\x129\n" +
	"\bJoinRoom\x12\x15.core.JoinRoomRequest\x1a\x16.core.JoinRoomResponse\x12B\n" +
	"\vGetMessages\x12\x18.core.GetMessagesRequest\x1a\x19.core.GetMessagesResponse\x12B\n" +
	"\vSetPresence\x12\x18.core.SetPresenceRequest\x1a\x19.core.SetPresenceResponse\x12<\n" +
	"\tSetTyping\x12\x16.core.SetTypingRequest\x1a\x17.core.SetTypingResponse\x12H\n" +
	"\rValidateToken\x12\x1a.core.ValidateTokenRequest\x1a\x1b.core.ValidateTokenResponse\x12Q\n" +
	"\x10GetPendingEvents\x12\x1d.core.GetPendingEventsRequest\x1a\x1e.core.GetPendingEventsResponse\x120\n" +
	"\bEventBus\x12\x15.core.EventBusRequest\x1a\v.core.Event0\x01\x12?\n" +
	"\n" +
	"GetMetrics\x12\x17.core.GetMetricsRequest\x1a\x18.core.GetMetricsResponse\x12E\n" +
	"\fGetRoomState\x12\x19.core.GetRoomStateRequest\x1a\x1a.core.GetRoomStateResponse\x12?\n" +
	"\n" +
	"InviteUser\x12\x17.core.InviteUserRequest\x1a\x18.core.InviteUserResponse\x12K\n" +
	"\x0eSetPowerLevels\x12\x1b.core.SetPowerLevelsRequest\x1a\x1c.core.SetPowerLevelsResponse\x12K\n" +
	"\x0eGetInitialSync\x12\x1b.core.GetInitialSyncRequest\x1a\x1c.core.GetInitialSyncResponse\x12E\n" +
	"\fGetSyncDelta\x12\x19.core.GetSyncDeltaRequest\x1a\x1a.core.GetSyncDeltaResponseB'Z%github.com/nebu/nebu/internal/grpc/pbb\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_core_proto_goTypes = []any{
	(*Event)(nil),                    // 0: core.Event
	(*SendEventRequest)(nil),         // 1: core.SendEventRequest
	(*SendEventResponse)(nil),        // 2: core.SendEventResponse
	(*CreateRoomRequest)(nil),        // 3: core.CreateRoomRequest
	(*CreateRoomResponse)(nil),       // 4: core.CreateRoomResponse
	(*JoinRoomRequest)(nil),          // 5: core.JoinRoomRequest
	(*JoinRoomResponse)(nil),         // 6: core.JoinRoomResponse
	(*GetMessagesRequest)(nil),       // 7: core.GetMessagesRequest
	(*GetMessagesResponse)(nil),      // 8: core.GetMessagesResponse
	(*SetPresenceRequest)(nil),       // 9: core.SetPresenceRequest
	(*SetPresenceResponse)(nil),      // 10: core.SetPresenceResponse
	(*SetTypingRequest)(nil),         // 11: core.SetTypingRequest
	(*SetTypingResponse)(nil),        // 12: core.SetTypingResponse
	(*ValidateTokenRequest)(nil),     // 13: core.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),    // 14: core.ValidateTokenResponse
	(*GetPendingEventsRequest)(nil),  // 15: core.GetPendingEventsRequest
	(*GetPendingEventsResponse)(nil), // 16: core.GetPendingEventsResponse
	(*EventBusRequest)(nil),          // 17: core.EventBusRequest
	(*GetMetricsRequest)(nil),        // 18: core.GetMetricsRequest
	(*GetMetricsResponse)(nil),       // 19: core.GetMetricsResponse
	(*InviteUserRequest)(nil),        // 20: core.InviteUserRequest
	(*InviteUserResponse)(nil),       // 21: core.InviteUserResponse
	(*GetRoomStateRequest)(nil),      // 22: core.GetRoomStateRequest
	(*GetRoomStateResponse)(nil),     // 23: core.GetRoomStateResponse
	(*SetPowerLevelsRequest)(nil),    // 24: core.SetPowerLevelsRequest
	(*SetPowerLevelsResponse)(nil),   // 25: core.SetPowerLevelsResponse
	(*GetInitialSyncRequest)(nil),    // 26: core.GetInitialSyncRequest
	(*GetInitialSyncResponse)(nil),   // 27: core.GetInitialSyncResponse
	(*SyncRoomStateEvent)(nil),       // 28: core.SyncRoomStateEvent
	(*GetSyncDeltaRequest)(nil),      // 29: core.GetSyncDeltaRequest
	(*GetSyncDeltaResponse)(nil),     // 30: core.GetSyncDeltaResponse
	(*SyncRoom)(nil),                 // 31: core.SyncRoom
}
var file_core_proto_depIdxs = []int32{
	0,  // 0: core.GetMessagesResponse.events:type_name -> core.Event
	0,  // 1: core.GetPendingEventsResponse.events:type_name -> core.Event
	31, // 2: core.GetInitialSyncResponse.rooms:type_name -> core.SyncRoom
	31, // 3: core.GetSyncDeltaResponse.rooms:type_name -> core.SyncRoom
	28, // 4: core.SyncRoom.state_events:type_name -> core.SyncRoomStateEvent
	0,  // 5: core.SyncRoom.timeline_events:type_name -> core.Event
	1,  // 6: core.CoreService.SendEvent:input_type -> core.SendEventRequest
	3,  // 7: core.CoreService.CreateRoom:input_type -> core.CreateRoomRequest
	5,  // 8: core.CoreService.JoinRoom:input_type -> core.JoinRoomRequest
	7,  // 9: core.CoreService.GetMessages:input_type -> core.GetMessagesRequest
	9,  // 10: core.CoreService.SetPresence:input_type -> core.SetPresenceRequest
	11, // 11: core.CoreService.SetTyping:input_type -> core.SetTypingRequest
	13, // 12: core.CoreService.ValidateToken:input_type -> core.ValidateTokenRequest
	15, // 13: core.CoreService.GetPendingEvents:input_type -> core.GetPendingEventsRequest
	17, // 14: core.CoreService.EventBus:input_type -> core.EventBusRequest
	18, // 15: core.CoreService.GetMetrics:input_type -> core.GetMetricsRequest
	22, // 16: core.CoreService.GetRoomState:input_type -> core.GetRoomStateRequest
	20, // 17: core.CoreService.InviteUser:input_type -> core.InviteUserRequest
	24, // 18: core.CoreService.SetPowerLevels:input_type -> core.SetPowerLevelsRequest
	26, // 19: core.CoreService.GetInitialSync:input_type -> core.GetInitialSyncRequest
	29, // 20: core.CoreService.GetSyncDelta:input_type -> core.GetSyncDeltaRequest
	2,  // 21: core.CoreService.SendEvent:output_type -> core.SendEventResponse
	4,  // 22: core.CoreService.CreateRoom:output_type -> core.CreateRoomResponse
	6,  // 23: core.CoreService.JoinRoom:output_type -> core.JoinRoomResponse
	8,  // 24: core.CoreService.GetMessages:output_type -> core.GetMessagesResponse
	10, // 25: core.CoreService.SetPresence:output_type -> core.SetPresenceResponse
	12, // 26: core.CoreService.SetTyping:output_type -> core.SetTypingResponse
	14, // 27: core.CoreService.ValidateToken:output_type -> core.ValidateTokenResponse
	16, // 28: core.CoreService.GetPendingEvents:output_type -> core.GetPendingEventsResponse
	0,  // 29: core.CoreService.EventBus:output_type -> core.Event
	19, // 30: core.CoreService.GetMetrics:output_type -> core.GetMetricsResponse
	23, // 31: core.CoreService.GetRoomState:output_type -> core.GetRoomStateResponse
	21, // 32: core.CoreService.InviteUser:output_type -> core.InviteUserResponse
	25, // 33: core.CoreService.SetPowerLevels:output_type -> core.SetPowerLevelsResponse
	27, // 34: core.CoreService.GetInitialSync:output_type -> core.GetInitialSyncResponse
	30, // 35: core.CoreService.GetSyncDelta:output_type -> core.GetSyncDeltaResponse
	21, // [21:36] is the sub-list for method output_type
	6,  // [6:21] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	file_core_proto_msgTypes[3].OneofWrappers = []any{}
	file_core_proto_msgTypes[7].OneofWrappers = []any{}
	file_core_proto_msgTypes[9].OneofWrappers = []any{}
	file_core_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
