// Story 7-27: ListPublicRoomsRequest / RoomSummary / ListPublicRoomsResponse are now fully
// generated by `make proto` (buf + protoc → core.pb.go). This file is intentionally empty.
// Previously contained hand-written structs; replaced after make proto ran for Story 6.5.
package pb
