name: Feature Request
description: Propose a new feature or enhancement for Nebu.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the problem you want to solve, not just the solution.
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this feature solve? What is the use case?
    validations:
      required: true
  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you would like.
    validations:
      required: true
  - type: textarea
    id: alternatives_considered
    attributes:
      label: Alternatives Considered
      description: >
        What alternative solutions or features have you considered?
  - type: checkboxes
    id: willing_to_contribute
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a pull request for this feature.
