//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for AssignUserRoleRequestAction.
const (
	Grant  AssignUserRoleRequestAction = "grant"
	Revoke AssignUserRoleRequestAction = "revoke"
)

// Valid indicates whether the value is a known member of the AssignUserRoleRequestAction enum.
func (e AssignUserRoleRequestAction) Valid() bool {
	switch e {
	case Grant:
		return true
	case Revoke:
		return true
	default:
		return false
	}
}

// Defines values for AssignUserRoleRequestRole.
const (
	ComplianceOfficer AssignUserRoleRequestRole = "compliance_officer"
	InstanceAdmin     AssignUserRoleRequestRole = "instance_admin"
)

// Valid indicates whether the value is a known member of the AssignUserRoleRequestRole enum.
func (e AssignUserRoleRequestRole) Valid() bool {
	switch e {
	case ComplianceOfficer:
		return true
	case InstanceAdmin:
		return true
	default:
		return false
	}
}

// Defines values for PatchAdminRoomRequestVisibility.
const (
	PatchAdminRoomRequestVisibilityPrivate PatchAdminRoomRequestVisibility = "private"
	PatchAdminRoomRequestVisibilityPublic  PatchAdminRoomRequestVisibility = "public"
)

// Valid indicates whether the value is a known member of the PatchAdminRoomRequestVisibility enum.
func (e PatchAdminRoomRequestVisibility) Valid() bool {
	switch e {
	case PatchAdminRoomRequestVisibilityPrivate:
		return true
	case PatchAdminRoomRequestVisibilityPublic:
		return true
	default:
		return false
	}
}

// Defines values for PutRoomDefaultsRequestDefaultVisibility.
const (
	PutRoomDefaultsRequestDefaultVisibilityPrivate PutRoomDefaultsRequestDefaultVisibility = "private"
	PutRoomDefaultsRequestDefaultVisibilityPublic  PutRoomDefaultsRequestDefaultVisibility = "public"
)

// Valid indicates whether the value is a known member of the PutRoomDefaultsRequestDefaultVisibility enum.
func (e PutRoomDefaultsRequestDefaultVisibility) Valid() bool {
	switch e {
	case PutRoomDefaultsRequestDefaultVisibilityPrivate:
		return true
	case PutRoomDefaultsRequestDefaultVisibilityPublic:
		return true
	default:
		return false
	}
}

// AdminRoomDetailObject defines model for AdminRoomDetailObject.
type AdminRoomDetailObject struct {
	CreatedAt       string `json:"created_at"`
	CreatorUserId   string `json:"creator_user_id"`
	MaxMembers      int    `json:"max_members"`
	MemberCount     int    `json:"member_count"`
	MessageCount    int    `json:"message_count"`
	Name            string `json:"name"`
	PowerLevelsJson string `json:"power_levels_json"`
	RoomId          string `json:"room_id"`
	Status          string `json:"status"`
	Topic           string `json:"topic"`
	Visibility      string `json:"visibility"`
}

// AdminRoomObject defines model for AdminRoomObject.
type AdminRoomObject struct {
	CreatedAt     string `json:"created_at"`
	CreatorUserId string `json:"creator_user_id"`
	MemberCount   int    `json:"member_count"`
	Name          string `json:"name"`
	RoomId        string `json:"room_id"`
	Status        string `json:"status"`
	Topic         string `json:"topic"`
	Visibility    string `json:"visibility"`
}

// AssignUserRoleRequest defines model for AssignUserRoleRequest.
type AssignUserRoleRequest struct {
	Action AssignUserRoleRequestAction `json:"action"`
	Role   AssignUserRoleRequestRole   `json:"role"`
}

// AssignUserRoleRequestAction defines model for AssignUserRoleRequest.Action.
type AssignUserRoleRequestAction string

// AssignUserRoleRequestRole defines model for AssignUserRoleRequest.Role.
type AssignUserRoleRequestRole string

// AssignUserRoleResponse defines model for AssignUserRoleResponse.
type AssignUserRoleResponse struct {
	Data struct {
		Action string `json:"action"`
		Role   string `json:"role"`
		UserId string `json:"user_id"`
	} `json:"data"`
}

// DeactivateUserRequest defines model for DeactivateUserRequest.
type DeactivateUserRequest struct {
	Reason string `json:"reason"`
}

// EmptyResponse Placeholder response; replaced in Epic 6 sub-stories
type EmptyResponse = map[string]interface{}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// PatchAdminRoomRequest defines model for PatchAdminRoomRequest.
type PatchAdminRoomRequest struct {
	MaxMembers *int                             `json:"max_members,omitempty"`
	Name       *string                          `json:"name,omitempty"`
	Topic      *string                          `json:"topic,omitempty"`
	Visibility *PatchAdminRoomRequestVisibility `json:"visibility,omitempty"`
}

// PatchAdminRoomRequestVisibility defines model for PatchAdminRoomRequest.Visibility.
type PatchAdminRoomRequestVisibility string

// PutRoomDefaultsRequest defines model for PutRoomDefaultsRequest.
type PutRoomDefaultsRequest struct {
	DefaultMaxMembers int                                     `json:"default_max_members"`
	DefaultVisibility PutRoomDefaultsRequestDefaultVisibility `json:"default_visibility"`
}

// PutRoomDefaultsRequestDefaultVisibility defines model for PutRoomDefaultsRequest.DefaultVisibility.
type PutRoomDefaultsRequestDefaultVisibility string

// RoomDefaultsResponse defines model for RoomDefaultsResponse.
type RoomDefaultsResponse struct {
	Data struct {
		DefaultMaxMembers int    `json:"default_max_members"`
		DefaultVisibility string `json:"default_visibility"`
	} `json:"data"`
}

// RoomListResponse defines model for RoomListResponse.
type RoomListResponse struct {
	Data []AdminRoomObject `json:"data"`
	Meta struct {
		NextCursor *string `json:"next_cursor,omitempty"`
		Total      int     `json:"total"`
	} `json:"meta"`
}

// RoomDetailResponse defines model for RoomDetailResponse.
type RoomDetailResponse struct {
	Data map[string]interface{} `json:"data"`
}

// RoomListResponse defines model for RoomListResponse.
type RoomListResponse struct {
	Data []map[string]interface{} `json:"data"`
	Meta struct {
		NextCursor *string `json:"next_cursor,omitempty"`
		Total      int     `json:"total"`
	} `json:"meta"`
}

// UserDetailResponse defines model for UserDetailResponse.
type UserDetailResponse struct {
	Data map[string]interface{} `json:"data"`
}

// UserListResponse defines model for UserListResponse.
type UserListResponse struct {
	Data []map[string]interface{} `json:"data"`
	Meta struct {
		NextCursor *string `json:"next_cursor,omitempty"`
		Total      int     `json:"total"`
	} `json:"meta"`
}

// UserStatusResponse defines model for UserStatusResponse.
type UserStatusResponse struct {
	Data struct {
		Status string `json:"status"`
		UserId string `json:"user_id"`
	} `json:"data"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListAdminRoomsParams defines parameters for ListAdminRooms.
type ListAdminRoomsParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Search *string `form:"search,omitempty" json:"search,omitempty"`
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// ListAdminUsersParams defines parameters for ListAdminUsers.
type ListAdminUsersParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// PutAdminRoomDefaultsJSONRequestBody defines body for PutAdminRoomDefaults for application/json ContentType.
type PutAdminRoomDefaultsJSONRequestBody = PutRoomDefaultsRequest

// PatchAdminRoomJSONRequestBody defines body for PatchAdminRoom for application/json ContentType.
type PatchAdminRoomJSONRequestBody = PatchAdminRoomRequest

// DeactivateAdminUserJSONRequestBody defines body for DeactivateAdminUser for application/json ContentType.
type DeactivateAdminUserJSONRequestBody = DeactivateUserRequest

// AssignAdminUserRoleJSONRequestBody defines body for AssignAdminUserRole for application/json ContentType.
type AssignAdminUserRoleJSONRequestBody = AssignUserRoleRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get server config (placeholder — Story 6.10)
	// (GET /admin/config)
	GetAdminConfig(w http.ResponseWriter, r *http.Request)
	// Set server-wide room defaults (instance_admin required)
	// (PUT /admin/config/room-defaults)
	PutAdminRoomDefaults(w http.ResponseWriter, r *http.Request)
	// Get metrics (placeholder — Story 6.10)
	// (GET /admin/metrics)
	GetAdminMetrics(w http.ResponseWriter, r *http.Request)
	// List rooms (instance_admin required)
	// (GET /admin/rooms)
	ListAdminRooms(w http.ResponseWriter, r *http.Request, params ListAdminRoomsParams)
	// Get single room (instance_admin required)
	// (GET /admin/rooms/{roomId})
	GetAdminRoom(w http.ResponseWriter, r *http.Request, roomId string)
	// Update room settings (instance_admin required)
	// (PATCH /admin/rooms/{roomId})
	PatchAdminRoom(w http.ResponseWriter, r *http.Request, roomId string)
	// List users (instance_admin required)
	// (GET /admin/users)
	ListAdminUsers(w http.ResponseWriter, r *http.Request, params ListAdminUsersParams)
	// Get single user (instance_admin required)
	// (GET /admin/users/{userId})
	GetAdminUser(w http.ResponseWriter, r *http.Request, userId string)
	// Deactivate user account (instance_admin required)
	// (POST /admin/users/{userId}/deactivate)
	DeactivateAdminUser(w http.ResponseWriter, r *http.Request, userId string)
	// Reactivate user account (instance_admin required)
	// (POST /admin/users/{userId}/reactivate)
	ReactivateAdminUser(w http.ResponseWriter, r *http.Request, userId string)
	// Grant or revoke a role override for a user (instance_admin required)
	// (POST /admin/users/{userId}/roles)
	AssignAdminUserRole(w http.ResponseWriter, r *http.Request, userId string)
	// List compliance access requests (placeholder — Story 6.x)
	// (GET /compliance/access-requests)
	ListComplianceAccessRequests(w http.ResponseWriter, r *http.Request)
	// Health check (unauthenticated)
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAdminConfig operation middleware
func (siw *ServerInterfaceWrapper) GetAdminConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutAdminRoomDefaults operation middleware
func (siw *ServerInterfaceWrapper) PutAdminRoomDefaults(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAdminRoomDefaults(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetAdminMetrics(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAdminRooms operation middleware
func (siw *ServerInterfaceWrapper) ListAdminRooms(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminRoomsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "search"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAdminRooms(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminRoom operation middleware
func (siw *ServerInterfaceWrapper) GetAdminRoom(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminRoom(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAdminRoom operation middleware
func (siw *ServerInterfaceWrapper) PatchAdminRoom(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAdminRoom(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAdminUsers operation middleware
func (siw *ServerInterfaceWrapper) ListAdminUsers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminUsersParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "search"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAdminUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminUser operation middleware
func (siw *ServerInterfaceWrapper) GetAdminUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeactivateAdminUser operation middleware
func (siw *ServerInterfaceWrapper) DeactivateAdminUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeactivateAdminUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReactivateAdminUser operation middleware
func (siw *ServerInterfaceWrapper) ReactivateAdminUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReactivateAdminUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AssignAdminUserRole operation middleware
func (siw *ServerInterfaceWrapper) AssignAdminUserRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AssignAdminUserRole(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListComplianceAccessRequests operation middleware
func (siw *ServerInterfaceWrapper) ListComplianceAccessRequests(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListComplianceAccessRequests(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/config", wrapper.GetAdminConfig)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/admin/config/room-defaults", wrapper.PutAdminRoomDefaults)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/metrics", wrapper.GetAdminMetrics)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/rooms", wrapper.ListAdminRooms)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/rooms/{roomId}", wrapper.GetAdminRoom)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/admin/rooms/{roomId}", wrapper.PatchAdminRoom)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/users", wrapper.ListAdminUsers)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/users/{userId}", wrapper.GetAdminUser)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/admin/users/{userId}/deactivate", wrapper.DeactivateAdminUser)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/admin/users/{userId}/reactivate", wrapper.ReactivateAdminUser)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/admin/users/{userId}/roles", wrapper.AssignAdminUserRole)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/compliance/access-requests", wrapper.ListComplianceAccessRequests)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)

	return m
}

type GetAdminConfigRequestObject struct {
}

type GetAdminConfigResponseObject interface {
	VisitGetAdminConfigResponse(w http.ResponseWriter) error
}

type GetAdminConfig200JSONResponse EmptyResponse

func (response GetAdminConfig200JSONResponse) VisitGetAdminConfigResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminConfig501Response struct {
}

func (response GetAdminConfig501Response) VisitGetAdminConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type PutAdminRoomDefaultsRequestObject struct {
	Body *PutAdminRoomDefaultsJSONRequestBody
}

type PutAdminRoomDefaultsResponseObject interface {
	VisitPutAdminRoomDefaultsResponse(w http.ResponseWriter) error
}

type PutAdminRoomDefaults200JSONResponse RoomDefaultsResponse

func (response PutAdminRoomDefaults200JSONResponse) VisitPutAdminRoomDefaultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutAdminRoomDefaults400JSONResponse EmptyResponse

func (response PutAdminRoomDefaults400JSONResponse) VisitPutAdminRoomDefaultsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutAdminRoomDefaults501Response struct {
}

func (response PutAdminRoomDefaults501Response) VisitPutAdminRoomDefaultsResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type GetAdminMetricsRequestObject struct {
}

type GetAdminMetricsResponseObject interface {
	VisitGetAdminMetricsResponse(w http.ResponseWriter) error
}

type GetAdminMetrics200JSONResponse EmptyResponse

func (response GetAdminMetrics200JSONResponse) VisitGetAdminMetricsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminMetrics501Response struct {
}

func (response GetAdminMetrics501Response) VisitGetAdminMetricsResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type ListAdminRoomsRequestObject struct {
	Params ListAdminRoomsParams
}

type ListAdminRoomsResponseObject interface {
	VisitListAdminRoomsResponse(w http.ResponseWriter) error
}

type ListAdminRooms200JSONResponse RoomListResponse

func (response ListAdminRooms200JSONResponse) VisitListAdminRoomsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAdminRooms400JSONResponse EmptyResponse

func (response ListAdminRooms400JSONResponse) VisitListAdminRoomsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListAdminRooms501Response struct {
}

func (response ListAdminRooms501Response) VisitListAdminRoomsResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type GetAdminRoomRequestObject struct {
	RoomId string `json:"roomId"`
}

type GetAdminRoomResponseObject interface {
	VisitGetAdminRoomResponse(w http.ResponseWriter) error
}

type GetAdminRoom200JSONResponse AdminRoomDetailObject

func (response GetAdminRoom200JSONResponse) VisitGetAdminRoomResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminRoom404JSONResponse EmptyResponse

func (response GetAdminRoom404JSONResponse) VisitGetAdminRoomResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminRoom501Response struct {
}

func (response GetAdminRoom501Response) VisitGetAdminRoomResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type PatchAdminRoomRequestObject struct {
	RoomId string `json:"roomId"`
	Body   *PatchAdminRoomJSONRequestBody
}

type PatchAdminRoomResponseObject interface {
	VisitPatchAdminRoomResponse(w http.ResponseWriter) error
}

type PatchAdminRoom200JSONResponse AdminRoomDetailObject

func (response PatchAdminRoom200JSONResponse) VisitPatchAdminRoomResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchAdminRoom400JSONResponse EmptyResponse

func (response PatchAdminRoom400JSONResponse) VisitPatchAdminRoomResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PatchAdminRoom404JSONResponse EmptyResponse

func (response PatchAdminRoom404JSONResponse) VisitPatchAdminRoomResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchAdminRoom501Response struct {
}

func (response PatchAdminRoom501Response) VisitPatchAdminRoomResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type ListAdminUsersRequestObject struct {
	Params ListAdminUsersParams
}

type ListAdminUsersResponseObject interface {
	VisitListAdminUsersResponse(w http.ResponseWriter) error
}

type ListAdminUsers200JSONResponse UserListResponse

func (response ListAdminUsers200JSONResponse) VisitListAdminUsersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAdminUsers400JSONResponse EmptyResponse

func (response ListAdminUsers400JSONResponse) VisitListAdminUsersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListAdminUsers501Response struct {
}

func (response ListAdminUsers501Response) VisitListAdminUsersResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type GetAdminUserRequestObject struct {
	UserId string `json:"userId"`
}

type GetAdminUserResponseObject interface {
	VisitGetAdminUserResponse(w http.ResponseWriter) error
}

type GetAdminUser200JSONResponse UserDetailResponse

func (response GetAdminUser200JSONResponse) VisitGetAdminUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAdminUser404JSONResponse EmptyResponse

func (response GetAdminUser404JSONResponse) VisitGetAdminUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeactivateAdminUserRequestObject struct {
	UserId string `json:"userId"`
	Body   *DeactivateAdminUserJSONRequestBody
}

type DeactivateAdminUserResponseObject interface {
	VisitDeactivateAdminUserResponse(w http.ResponseWriter) error
}

type DeactivateAdminUser200JSONResponse UserStatusResponse

func (response DeactivateAdminUser200JSONResponse) VisitDeactivateAdminUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeactivateAdminUser400JSONResponse EmptyResponse

func (response DeactivateAdminUser400JSONResponse) VisitDeactivateAdminUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeactivateAdminUser404JSONResponse EmptyResponse

func (response DeactivateAdminUser404JSONResponse) VisitDeactivateAdminUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeactivateAdminUser409JSONResponse EmptyResponse

func (response DeactivateAdminUser409JSONResponse) VisitDeactivateAdminUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeactivateAdminUser501Response struct {
}

func (response DeactivateAdminUser501Response) VisitDeactivateAdminUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type ReactivateAdminUserRequestObject struct {
	UserId string `json:"userId"`
}

type ReactivateAdminUserResponseObject interface {
	VisitReactivateAdminUserResponse(w http.ResponseWriter) error
}

type ReactivateAdminUser200JSONResponse UserStatusResponse

func (response ReactivateAdminUser200JSONResponse) VisitReactivateAdminUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReactivateAdminUser404JSONResponse EmptyResponse

func (response ReactivateAdminUser404JSONResponse) VisitReactivateAdminUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ReactivateAdminUser409JSONResponse EmptyResponse

func (response ReactivateAdminUser409JSONResponse) VisitReactivateAdminUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ReactivateAdminUser501Response struct {
}

func (response ReactivateAdminUser501Response) VisitReactivateAdminUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type AssignAdminUserRoleRequestObject struct {
	UserId string `json:"userId"`
	Body   *AssignAdminUserRoleJSONRequestBody
}

type AssignAdminUserRoleResponseObject interface {
	VisitAssignAdminUserRoleResponse(w http.ResponseWriter) error
}

type AssignAdminUserRole200JSONResponse AssignUserRoleResponse

func (response AssignAdminUserRole200JSONResponse) VisitAssignAdminUserRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AssignAdminUserRole400JSONResponse EmptyResponse

func (response AssignAdminUserRole400JSONResponse) VisitAssignAdminUserRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AssignAdminUserRole403JSONResponse EmptyResponse

func (response AssignAdminUserRole403JSONResponse) VisitAssignAdminUserRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type AssignAdminUserRole404JSONResponse EmptyResponse

func (response AssignAdminUserRole404JSONResponse) VisitAssignAdminUserRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AssignAdminUserRole501Response struct {
}

func (response AssignAdminUserRole501Response) VisitAssignAdminUserRoleResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type ListComplianceAccessRequestsRequestObject struct {
}

type ListComplianceAccessRequestsResponseObject interface {
	VisitListComplianceAccessRequestsResponse(w http.ResponseWriter) error
}

type ListComplianceAccessRequests200JSONResponse EmptyResponse

func (response ListComplianceAccessRequests200JSONResponse) VisitListComplianceAccessRequestsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListComplianceAccessRequests501Response struct {
}

func (response ListComplianceAccessRequests501Response) VisitListComplianceAccessRequestsResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get server config (placeholder — Story 6.10)
	// (GET /admin/config)
	GetAdminConfig(ctx context.Context, request GetAdminConfigRequestObject) (GetAdminConfigResponseObject, error)
	// Set server-wide room defaults (instance_admin required)
	// (PUT /admin/config/room-defaults)
	PutAdminRoomDefaults(ctx context.Context, request PutAdminRoomDefaultsRequestObject) (PutAdminRoomDefaultsResponseObject, error)
	// Get metrics (placeholder — Story 6.10)
	// (GET /admin/metrics)
	GetAdminMetrics(ctx context.Context, request GetAdminMetricsRequestObject) (GetAdminMetricsResponseObject, error)
	// List rooms (instance_admin required)
	// (GET /admin/rooms)
	ListAdminRooms(ctx context.Context, request ListAdminRoomsRequestObject) (ListAdminRoomsResponseObject, error)
	// Get single room (instance_admin required)
	// (GET /admin/rooms/{roomId})
	GetAdminRoom(ctx context.Context, request GetAdminRoomRequestObject) (GetAdminRoomResponseObject, error)
	// Update room settings (instance_admin required)
	// (PATCH /admin/rooms/{roomId})
	PatchAdminRoom(ctx context.Context, request PatchAdminRoomRequestObject) (PatchAdminRoomResponseObject, error)
	// List users (instance_admin required)
	// (GET /admin/users)
	ListAdminUsers(ctx context.Context, request ListAdminUsersRequestObject) (ListAdminUsersResponseObject, error)
	// Get single user (instance_admin required)
	// (GET /admin/users/{userId})
	GetAdminUser(ctx context.Context, request GetAdminUserRequestObject) (GetAdminUserResponseObject, error)
	// Deactivate user account (instance_admin required)
	// (POST /admin/users/{userId}/deactivate)
	DeactivateAdminUser(ctx context.Context, request DeactivateAdminUserRequestObject) (DeactivateAdminUserResponseObject, error)
	// Reactivate user account (instance_admin required)
	// (POST /admin/users/{userId}/reactivate)
	ReactivateAdminUser(ctx context.Context, request ReactivateAdminUserRequestObject) (ReactivateAdminUserResponseObject, error)
	// Grant or revoke a role override for a user (instance_admin required)
	// (POST /admin/users/{userId}/roles)
	AssignAdminUserRole(ctx context.Context, request AssignAdminUserRoleRequestObject) (AssignAdminUserRoleResponseObject, error)
	// List compliance access requests (placeholder — Story 6.x)
	// (GET /compliance/access-requests)
	ListComplianceAccessRequests(ctx context.Context, request ListComplianceAccessRequestsRequestObject) (ListComplianceAccessRequestsResponseObject, error)
	// Health check (unauthenticated)
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAdminConfig operation middleware
func (sh *strictHandler) GetAdminConfig(w http.ResponseWriter, r *http.Request) {
	var request GetAdminConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminConfig(ctx, request.(GetAdminConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminConfigResponseObject); ok {
		if err := validResponse.VisitGetAdminConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutAdminRoomDefaults operation middleware
func (sh *strictHandler) PutAdminRoomDefaults(w http.ResponseWriter, r *http.Request) {
	var request PutAdminRoomDefaultsRequestObject

	var body PutAdminRoomDefaultsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutAdminRoomDefaults(ctx, request.(PutAdminRoomDefaultsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutAdminRoomDefaults")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutAdminRoomDefaultsResponseObject); ok {
		if err := validResponse.VisitPutAdminRoomDefaultsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminMetrics operation middleware
func (sh *strictHandler) GetAdminMetrics(w http.ResponseWriter, r *http.Request) {
	var request GetAdminMetricsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminMetrics(ctx, request.(GetAdminMetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminMetrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminMetricsResponseObject); ok {
		if err := validResponse.VisitGetAdminMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAdminRooms operation middleware
func (sh *strictHandler) ListAdminRooms(w http.ResponseWriter, r *http.Request, params ListAdminRoomsParams) {
	var request ListAdminRoomsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAdminRooms(ctx, request.(ListAdminRoomsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAdminRooms")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAdminRoomsResponseObject); ok {
		if err := validResponse.VisitListAdminRoomsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminRoom operation middleware
func (sh *strictHandler) GetAdminRoom(w http.ResponseWriter, r *http.Request, roomId string) {
	var request GetAdminRoomRequestObject

	request.RoomId = roomId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminRoom(ctx, request.(GetAdminRoomRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminRoom")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminRoomResponseObject); ok {
		if err := validResponse.VisitGetAdminRoomResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchAdminRoom operation middleware
func (sh *strictHandler) PatchAdminRoom(w http.ResponseWriter, r *http.Request, roomId string) {
	var request PatchAdminRoomRequestObject

	request.RoomId = roomId

	var body PatchAdminRoomJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchAdminRoom(ctx, request.(PatchAdminRoomRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchAdminRoom")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchAdminRoomResponseObject); ok {
		if err := validResponse.VisitPatchAdminRoomResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAdminUsers operation middleware
func (sh *strictHandler) ListAdminUsers(w http.ResponseWriter, r *http.Request, params ListAdminUsersParams) {
	var request ListAdminUsersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAdminUsers(ctx, request.(ListAdminUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAdminUsers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAdminUsersResponseObject); ok {
		if err := validResponse.VisitListAdminUsersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminUser operation middleware
func (sh *strictHandler) GetAdminUser(w http.ResponseWriter, r *http.Request, userId string) {
	var request GetAdminUserRequestObject

	request.UserId = userId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminUser(ctx, request.(GetAdminUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminUserResponseObject); ok {
		if err := validResponse.VisitGetAdminUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeactivateAdminUser operation middleware
func (sh *strictHandler) DeactivateAdminUser(w http.ResponseWriter, r *http.Request, userId string) {
	var request DeactivateAdminUserRequestObject

	request.UserId = userId

	var body DeactivateAdminUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeactivateAdminUser(ctx, request.(DeactivateAdminUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeactivateAdminUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeactivateAdminUserResponseObject); ok {
		if err := validResponse.VisitDeactivateAdminUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReactivateAdminUser operation middleware
func (sh *strictHandler) ReactivateAdminUser(w http.ResponseWriter, r *http.Request, userId string) {
	var request ReactivateAdminUserRequestObject

	request.UserId = userId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReactivateAdminUser(ctx, request.(ReactivateAdminUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReactivateAdminUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReactivateAdminUserResponseObject); ok {
		if err := validResponse.VisitReactivateAdminUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AssignAdminUserRole operation middleware
func (sh *strictHandler) AssignAdminUserRole(w http.ResponseWriter, r *http.Request, userId string) {
	var request AssignAdminUserRoleRequestObject

	request.UserId = userId

	var body AssignAdminUserRoleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AssignAdminUserRole(ctx, request.(AssignAdminUserRoleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AssignAdminUserRole")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AssignAdminUserRoleResponseObject); ok {
		if err := validResponse.VisitAssignAdminUserRoleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListComplianceAccessRequests operation middleware
func (sh *strictHandler) ListComplianceAccessRequests(w http.ResponseWriter, r *http.Request) {
	var request ListComplianceAccessRequestsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListComplianceAccessRequests(ctx, request.(ListComplianceAccessRequestsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListComplianceAccessRequests")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListComplianceAccessRequestsResponseObject); ok {
		if err := validResponse.VisitListComplianceAccessRequestsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Frdbtu2F38Vgv//RQoosd0vYN5V+rV16NogWbeLIDBo6dhmS5HqIeXGMAzsIfaEe5KBpGRLNmUrTuM0",
	"W29SS+ThOb/zOx+kOKexSjMlQRpN+3Oq4wmkzP33NEm5PFcqfQWGcfFh+AliY18wIT6MaP9yTv+PMKJ9",
	"+r/OSkinkNBZTi8mLqI5zVBlgIaDWyBl14MU0iGg+2lmGdA+5dLAGJAuIpqC1mwMg1jl0oSHZOor4EDA",
	"FIQefNJKVoZpg1yO6WIRUYQvOUdIaP+ytuz6GiGBV1EpUBWWXC0ium5ef926GIEZSAbMBFSK/GuFg1wD",
	"DngSHOO13Ga+ZCkEp6JSaZNYbZjJdfCVURmPg2+mXPMhF9zMdiNcLl7oV4qtCVmzbqlVVAVuE6ZNZ0T0",
	"VGs+lh814LkScA5fctABh7DYcM8PkHlq9Rwjc0sjTNVnqMiu4iigOoVLbZiMYcCs/62CKs0Ed4/UaMRj",
	"wICcDXyERaVQqI1JOlNSw6ZNCTNsm6WN9my8aObhmvLlwGinGWsTna4hY1+BFTFlBpzBTf5DYEV8p1y+",
	"Azk2E9rvdXeC7aeFFn6dZmZWBTcBHSPPPHr0TLAYJkokgASLUT8ShMw+TwiX5HXGY/Kc6Hx4rI1Cq2hg",
	"mZ+BCTNpdmJjPK5ZUowLWXLGTDxZpqRGCNcybsqueWp53evaf5EF1j94HG1JNim7LuF//OxZVHNHtCWn",
	"VOb13HI7kkwZc1k+FC59ZOhYEg6wTUxy46vXiOXC6EZQEj9gsA5OiUU3hEU56TYa14IjoERwlZD362be",
	"LFc0WN/W4juzqm3ysLa/49rstpsbSN2Dm3Ut5ZIMkc18VQ7hKOHaDOIctcKGymqYCCG7Zqgf1w6PQpcQ",
	"LDaT+r5tNzB7Im+XuCHyGzIeLLYXLhffNNi2dF571N/GetDOg7YThDhHbmYXlv1exRfAEPA0t1l6Tofu",
	"1xuFqW1j6S9//GbXdaNpv3i7KnkTYzK6sIK5HClnCje236DvYZgTF1vk9Oyt7QQBta+yvZPuSdcioDKQ",
	"LOO0T5+c9E66NnsyM3FKdVy31YmVHPGxfTAGl8gttsxW67cJ7dOfwLglXvphFgTvHifjcbfr2nIlDfh2",
	"mmWZ4LGb3ym3Dj4P7MoS9cbBWVxvHQoVFhF91u1tdhbvlSE8zQSkIA0k3hd5mjKceTuIBpwCEm8xOcoq",
	"rcjff/5FLozCGXl+0us+cpNrAHVs/31cZFlne5YH4DrLTWWLVwz2zAFtXqhk9s3waijFizpTDeawuEOv",
	"BctkwHl2HFnCt4jo00NS53cmeOIkE0BUuCeJLpYkOv7KEyBYNYoc1fcxpHRCjU0pGOSx3hlvvxbj7jPg",
	"Sh32j7jC2taxZgFtxsYWxmV0aZfLkKVgXHt1OafcKvUlB5yVu+Q+LSpcVMFkoxSEZwqechOaWKmE4Zka",
	"GMaTfdZc7tebZ17dcTDXuo+mQBZcm4MH8QuWkCKR2lib2pgm3r9EIXH+erQnWa3VLpxbhrEb2pnbP2+T",
	"xc5otqA18NXW4xUBvEC6nsHvixDh48rm9G4HFdn96eGI4RaXypCRymVymwaBy7Eo0voWGrgmKp4Eqn/t",
	"xOBOHX4H/UTwuOPA7URrwn3MEmYgcb76LtqJh8d4D6FnuwZjuBy3zH52u9SiTH/U/mzi4Zbpu8ytG1v9",
	"EMs14L+02DoO3YBunbn906bYWtBa5V4v8LsptoHjpSZK3FeldYtX8k5TBbXI7uPbTrL8bOG22EoH/Lz6",
	"tHEYd3/7Uhv+OHPgUhs4cWumW6lvcr+JKOXaMqyjJwoN8V+hHt17FNjlfzjsOZjgsSFHTCCwZFb1z745",
	"eUVJH7wsdt+Q9wpibBHE5wcO4vsPIlwPov8iYzkiuGPqoQCijaWbQlLy2AEE+1L4/FtSWAlPljB7/VWC",
	"JXPP/Uf7h1SCwvc7Dr3bC9/ICG54BBDmhkNiKeOvlyTfR19s2eJ47G5tFAXpyeGUeqNwyJMEJDnSIEbH",
	"HhySoTJQVenQGcf6yUEzBUSewO0PaZBJs3I/YWvyR9YJrbrP1RWjDotj0Pq48Or2fe3L5bRTN+u8nHSf",
	"5/ReFbI04Ba7shUshNWlNp/hXxeQTtyVnG3bM39p5y6xWrsWFADLjyDFSXv1gy3tX15VASlGxhOIP5Oj",
	"XLLcTEAaq5inUX1u/TPv5ZXN3P5jkS8HOQrapx2W8c60RxdXi38CAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
