//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// EmptyResponse Placeholder response; replaced in Epic 6 sub-stories
type EmptyResponse = map[string]interface{}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// UserDetailResponse defines model for UserDetailResponse.
type UserDetailResponse struct {
	Data map[string]interface{} `json:"data"`
}

// UserListResponse defines model for UserListResponse.
type UserListResponse struct {
	Data []map[string]interface{} `json:"data"`
	Meta struct {
		NextCursor *string `json:"next_cursor,omitempty"`
		Total      int     `json:"total"`
	} `json:"meta"`
}

// ListAdminUsersParams defines parameters for ListAdminUsers.
type ListAdminUsersParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get server config (placeholder — Story 6.10)
	// (GET /admin/config)
	GetAdminConfig(w http.ResponseWriter, r *http.Request)
	// Get metrics (placeholder — Story 6.10)
	// (GET /admin/metrics)
	GetAdminMetrics(w http.ResponseWriter, r *http.Request)
	// List rooms (placeholder — Story 6.7)
	// (GET /admin/rooms)
	ListAdminRooms(w http.ResponseWriter, r *http.Request)
	// List users (instance_admin required)
	// (GET /admin/users)
	ListAdminUsers(w http.ResponseWriter, r *http.Request, params ListAdminUsersParams)
	// Get single user (instance_admin required)
	// (GET /admin/users/{userId})
	GetAdminUser(w http.ResponseWriter, r *http.Request, userId string)
	// List compliance access requests (placeholder — Story 6.x)
	// (GET /compliance/access-requests)
	ListComplianceAccessRequests(w http.ResponseWriter, r *http.Request)
	// Health check (unauthenticated)
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAdminConfig operation middleware
func (siw *ServerInterfaceWrapper) GetAdminConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetAdminMetrics(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAdminRooms operation middleware
func (siw *ServerInterfaceWrapper) ListAdminRooms(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAdminRooms(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAdminUsers operation middleware
func (siw *ServerInterfaceWrapper) ListAdminUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminUsersParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAdminUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminUser operation middleware
func (siw *ServerInterfaceWrapper) GetAdminUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListComplianceAccessRequests operation middleware
func (siw *ServerInterfaceWrapper) ListComplianceAccessRequests(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListComplianceAccessRequests(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/admin/config", wrapper.GetAdminConfig)
	m.HandleFunc("GET "+options.BaseURL+"/admin/metrics", wrapper.GetAdminMetrics)
	m.HandleFunc("GET "+options.BaseURL+"/admin/rooms", wrapper.ListAdminRooms)
	m.HandleFunc("GET "+options.BaseURL+"/admin/users", wrapper.ListAdminUsers)
	m.HandleFunc("GET "+options.BaseURL+"/admin/users/{userId}", wrapper.GetAdminUser)
	m.HandleFunc("GET "+options.BaseURL+"/compliance/access-requests", wrapper.ListComplianceAccessRequests)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)

	return m
}

type GetAdminConfigRequestObject struct {
}

type GetAdminConfigResponseObject interface {
	VisitGetAdminConfigResponse(w http.ResponseWriter) error
}

type GetAdminConfig200JSONResponse EmptyResponse

func (response GetAdminConfig200JSONResponse) VisitGetAdminConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminConfig501Response struct {
}

func (response GetAdminConfig501Response) VisitGetAdminConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type GetAdminMetricsRequestObject struct {
}

type GetAdminMetricsResponseObject interface {
	VisitGetAdminMetricsResponse(w http.ResponseWriter) error
}

type GetAdminMetrics200JSONResponse EmptyResponse

func (response GetAdminMetrics200JSONResponse) VisitGetAdminMetricsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminMetrics501Response struct {
}

func (response GetAdminMetrics501Response) VisitGetAdminMetricsResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type ListAdminRoomsRequestObject struct {
}

type ListAdminRoomsResponseObject interface {
	VisitListAdminRoomsResponse(w http.ResponseWriter) error
}

type ListAdminRooms200JSONResponse EmptyResponse

func (response ListAdminRooms200JSONResponse) VisitListAdminRoomsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListAdminRooms501Response struct {
}

func (response ListAdminRooms501Response) VisitListAdminRoomsResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type ListAdminUsersRequestObject struct {
	Params ListAdminUsersParams
}

type ListAdminUsersResponseObject interface {
	VisitListAdminUsersResponse(w http.ResponseWriter) error
}

type ListAdminUsers200JSONResponse UserListResponse

func (response ListAdminUsers200JSONResponse) VisitListAdminUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListAdminUsers400JSONResponse EmptyResponse

func (response ListAdminUsers400JSONResponse) VisitListAdminUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListAdminUsers501Response struct {
}

func (response ListAdminUsers501Response) VisitListAdminUsersResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type GetAdminUserRequestObject struct {
	UserId string `json:"userId"`
}

type GetAdminUserResponseObject interface {
	VisitGetAdminUserResponse(w http.ResponseWriter) error
}

type GetAdminUser200JSONResponse UserDetailResponse

func (response GetAdminUser200JSONResponse) VisitGetAdminUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminUser404JSONResponse EmptyResponse

func (response GetAdminUser404JSONResponse) VisitGetAdminUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListComplianceAccessRequestsRequestObject struct {
}

type ListComplianceAccessRequestsResponseObject interface {
	VisitListComplianceAccessRequestsResponse(w http.ResponseWriter) error
}

type ListComplianceAccessRequests200JSONResponse EmptyResponse

func (response ListComplianceAccessRequests200JSONResponse) VisitListComplianceAccessRequestsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListComplianceAccessRequests501Response struct {
}

func (response ListComplianceAccessRequests501Response) VisitListComplianceAccessRequestsResponse(w http.ResponseWriter) error {
	w.WriteHeader(501)
	return nil
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get server config (placeholder — Story 6.10)
	// (GET /admin/config)
	GetAdminConfig(ctx context.Context, request GetAdminConfigRequestObject) (GetAdminConfigResponseObject, error)
	// Get metrics (placeholder — Story 6.10)
	// (GET /admin/metrics)
	GetAdminMetrics(ctx context.Context, request GetAdminMetricsRequestObject) (GetAdminMetricsResponseObject, error)
	// List rooms (placeholder — Story 6.7)
	// (GET /admin/rooms)
	ListAdminRooms(ctx context.Context, request ListAdminRoomsRequestObject) (ListAdminRoomsResponseObject, error)
	// List users (instance_admin required)
	// (GET /admin/users)
	ListAdminUsers(ctx context.Context, request ListAdminUsersRequestObject) (ListAdminUsersResponseObject, error)
	// Get single user (instance_admin required)
	// (GET /admin/users/{userId})
	GetAdminUser(ctx context.Context, request GetAdminUserRequestObject) (GetAdminUserResponseObject, error)
	// List compliance access requests (placeholder — Story 6.x)
	// (GET /compliance/access-requests)
	ListComplianceAccessRequests(ctx context.Context, request ListComplianceAccessRequestsRequestObject) (ListComplianceAccessRequestsResponseObject, error)
	// Health check (unauthenticated)
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAdminConfig operation middleware
func (sh *strictHandler) GetAdminConfig(w http.ResponseWriter, r *http.Request) {
	var request GetAdminConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminConfig(ctx, request.(GetAdminConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminConfigResponseObject); ok {
		if err := validResponse.VisitGetAdminConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminMetrics operation middleware
func (sh *strictHandler) GetAdminMetrics(w http.ResponseWriter, r *http.Request) {
	var request GetAdminMetricsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminMetrics(ctx, request.(GetAdminMetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminMetrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminMetricsResponseObject); ok {
		if err := validResponse.VisitGetAdminMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAdminRooms operation middleware
func (sh *strictHandler) ListAdminRooms(w http.ResponseWriter, r *http.Request) {
	var request ListAdminRoomsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAdminRooms(ctx, request.(ListAdminRoomsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAdminRooms")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAdminRoomsResponseObject); ok {
		if err := validResponse.VisitListAdminRoomsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAdminUsers operation middleware
func (sh *strictHandler) ListAdminUsers(w http.ResponseWriter, r *http.Request, params ListAdminUsersParams) {
	var request ListAdminUsersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAdminUsers(ctx, request.(ListAdminUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAdminUsers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAdminUsersResponseObject); ok {
		if err := validResponse.VisitListAdminUsersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAdminUser operation middleware
func (sh *strictHandler) GetAdminUser(w http.ResponseWriter, r *http.Request, userId string) {
	var request GetAdminUserRequestObject

	request.UserId = userId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminUser(ctx, request.(GetAdminUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAdminUserResponseObject); ok {
		if err := validResponse.VisitGetAdminUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListComplianceAccessRequests operation middleware
func (sh *strictHandler) ListComplianceAccessRequests(w http.ResponseWriter, r *http.Request) {
	var request ListComplianceAccessRequestsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListComplianceAccessRequests(ctx, request.(ListComplianceAccessRequestsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListComplianceAccessRequests")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListComplianceAccessRequestsResponseObject); ok {
		if err := validResponse.VisitListComplianceAccessRequestsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RW227cNhN+FWL+/8IBlNVum6aAeuWkaeuiDQKnQS+MRUBT4xVTiWSGIyMLY4E+RJ+w",
	"T1IMqbW1Xq0dJEh8pQPn+M03w7kC47vgHTqOUF1BNA12Or2+6AKvTzEG7yLKjxqjIRvYegcVvGq1wca3",
	"NZKiQeoHRRjkf62sUy+CNeqpiv3548ieLEYogNcBoQJ//g4Nw6aAX1C33Iz9BPIBiUVeImLNfXobVCOT",
	"dSvYbAogfN9bwhqqs63ccsLFm4j0I7K27WE3tWY9crJVvuUkSR1y8ZuNfL8Dy9jFCU/XRjWRXst3h1lj",
	"147DD/zW9BQ9TYBSAHvW7ejEOsYV0l4qWW4/l6mMh1gmhSOaniyvXwtzcojPUBPScc+NfJ2nr588dZqh",
	"gl///AOKzDOxlE9viNEwB9iIYesufMrDcisnL/G8V8d1Z506fnUCBVwixczFxWw+m0vyPqDTwUIF384W",
	"szkUEDQ3KahSi2ppvLuwK/mxQpaHYKuF0yc1VPAzcnLxPIsJFrmgycY387k8jHeMLmnrEFprkn75Lkow",
	"2x6St/8TXkAF/ytvmqwcOqzcba+U8W6DDSFsCvhuvtjvv5eele1Cix06xjrXou86Teuch4pIl0gqZ6yO",
	"wqhh//37H/WaPa3V09li/igpDwB1yGRNvBeh3we5h4RoG8OnYzRk+9HokPfdYWxkAiRwTpPYQ0IjEajW",
	"Rv5EcCQVlbI9jM33O9D0EekjoHmTxKQxSXfISefsCqyE9L5HWkMBTqfZMEy5YoTJ3h0wrdnazvKU4mga",
	"TmtG1GSaO30uv2Bd9+6RidKKzHVpn3xNUj3TtZLLASOrI+sudWtrlaukvMTUWX70OYRLHBLTkbUz+DYx",
	"S23vo326lVfyOKk3944rAe0A6+SKuCFANgjjW5Cpx4ckxK3d5RAl6iQWMyuefD1WJOfOs7rwvZu8iKxb",
	"tZiKe19txX9r5bzUxmCMjwe+3T1Znl+rHSet063SQ47gHIq6TuAz+uIGFqV3rR6ezh8GSJu0YN/VIHkF",
	"/5JY3VryJ8DKEmrY4seLJVRnyzEgg6Rp0Pyljnqne27QsQSWabSru7uOni2lW/NmlEdATy1UUOpgy8sF",
	"bJab/wIAAP//hL0gshMNAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
