//go:build integration

package integration_test

// Story 12.1 — MinIO Docker Compose + Credentials via Secrets
//
// These tests verify that the MinIO service is correctly integrated into the
// Docker Compose stack with credentials managed via Docker Secrets, and that
// no credentials are committed to Git.
//
// Build tag: integration — run with:
//
//	go test -tags=integration ./test/integration/... -v -run TestMinIO_
//
// All tests perform static analysis (no running containers required) except
// where explicitly noted.
//
// TDD RED PHASE: All tests in this file are designed to FAIL until the
// implementation in docker-compose.yml, Makefile, README, and ADR-013 is complete.

import (
	"encoding/json"
	"os"
	"os/exec"
	"strings"
	"testing"
)

// projectRootForMinio resolves the project root from the test binary location.
// Integration tests run from gateway/test/integration, so project root is 3 levels up.
func projectRootForMinio() string {
	root := os.Getenv("NEBU_PROJECT_ROOT")
	if root == "" {
		root = "../../../"
	}
	return root
}

// TestMinIO_ServiceDefinedInCompose — AC1
//
// Given: docker-compose.yml is updated
// When:  `docker compose config --format json` is parsed
// Then:  a `minio` service entry exists with `minio_root_user` and `minio_root_password` secrets
//
// FAILS until docker-compose.yml includes the `minio` service and both secrets.
func TestMinIO_ServiceDefinedInCompose(t *testing.T) {
	projectRoot := projectRootForMinio()
	composeFile := projectRoot + "docker-compose.yml"

	if _, err := os.Stat(composeFile); os.IsNotExist(err) {
		t.Skipf("docker-compose.yml not found at %s — set NEBU_PROJECT_ROOT env var", composeFile)
	}

	// Try docker compose config for structured validation.
	if _, err := exec.LookPath("docker"); err != nil {
		t.Log("docker not available — falling back to string-based check")
		checkComposeFileForMinio(t, composeFile)
		return
	}

	cmd := exec.Command("docker", "compose", "-f", composeFile, "config", "--format", "json")
	out, err := cmd.Output()
	if err != nil {
		t.Logf("docker compose config failed (%v), falling back to file parse", err)
		checkComposeFileForMinio(t, composeFile)
		return
	}

	var cfg struct {
		Services map[string]json.RawMessage `json:"services"`
		Secrets  map[string]json.RawMessage `json:"secrets"`
	}
	if err := json.Unmarshal(out, &cfg); err != nil {
		t.Logf("JSON parse failed (%v), falling back to string check", err)
		checkComposeFileForMinio(t, composeFile)
		return
	}

	// AC1: minio service must exist
	if _, ok := cfg.Services["minio"]; !ok {
		t.Error("AC1 FAIL: `minio` service is missing from docker-compose.yml — add a MinIO service")
	} else {
		t.Log("AC1 PASS: `minio` service found in docker-compose.yml")
	}

	// AC2 (partial): minio_root_user and minio_root_password must be declared as top-level secrets
	if _, ok := cfg.Secrets["minio_root_user"]; !ok {
		t.Error("AC2 FAIL: `minio_root_user` secret is missing from docker-compose.yml secrets block")
	} else {
		t.Log("AC2 PASS: `minio_root_user` secret declared")
	}

	if _, ok := cfg.Secrets["minio_root_password"]; !ok {
		t.Error("AC2 FAIL: `minio_root_password` secret is missing from docker-compose.yml secrets block")
	} else {
		t.Log("AC2 PASS: `minio_root_password` secret declared")
	}
}

// checkComposeFileForMinio is a fallback string-based check when docker is unavailable.
func checkComposeFileForMinio(t *testing.T, composeFile string) {
	t.Helper()
	data, err := os.ReadFile(composeFile)
	if err != nil {
		t.Fatalf("cannot read docker-compose.yml: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, "minio:") {
		t.Error("AC1 FAIL: `minio:` service definition not found in docker-compose.yml")
	} else {
		t.Log("AC1 PASS: minio service found (string check)")
	}

	if !strings.Contains(content, "minio_root_user") {
		t.Error("AC2 FAIL: `minio_root_user` secret not found in docker-compose.yml")
	} else {
		t.Log("AC2 PASS: minio_root_user found (string check)")
	}

	if !strings.Contains(content, "minio_root_password") {
		t.Error("AC2 FAIL: `minio_root_password` secret not found in docker-compose.yml")
	} else {
		t.Log("AC2 PASS: minio_root_password found (string check)")
	}
}

// TestMinIO_SecretsFilesGenerated — AC2
//
// Given: `.secrets/minio_root_user` and `.secrets/minio_root_password` are generated by `make setup`
// When:  both files are read
// Then:  each file exists and contains a non-empty value (≥8 characters)
//
// FAILS until `make setup` is updated to generate these two credential files.
// Run `make setup` before running this test.
func TestMinIO_SecretsFilesGenerated(t *testing.T) {
	projectRoot := projectRootForMinio()

	files := []struct {
		path    string
		label   string
		minLen  int
	}{
		{projectRoot + ".secrets/minio_root_user", "MINIO_ROOT_USER", 8},
		{projectRoot + ".secrets/minio_root_password", "MINIO_ROOT_PASSWORD", 8},
	}

	for _, f := range files {
		data, err := os.ReadFile(f.path)
		if err != nil {
			t.Errorf("AC2 FAIL: %s not found at %s — run `make setup` to generate it (err: %v)",
				f.label, f.path, err)
			continue
		}

		val := strings.TrimSpace(string(data))
		if len(val) < f.minLen {
			t.Errorf("AC2 FAIL: %s at %s is too short (%d chars, need ≥%d) — check `make setup`",
				f.label, f.path, len(val), f.minLen)
		} else {
			t.Logf("AC2 PASS: %s exists with %d chars", f.label, len(val))
		}
	}
}

// TestMinIO_GitignoreExcludesSecrets — AC3
//
// Given: `.gitignore` is inspected
// When:  `.secrets/` is listed
// Then:  it is excluded from Git tracking
//
// This test verifies that the `.secrets/` pattern remains in `.gitignore`.
// PASSES already if .gitignore is unchanged — this is a regression guard.
func TestMinIO_GitignoreExcludesSecrets(t *testing.T) {
	projectRoot := projectRootForMinio()
	gitignore := projectRoot + ".gitignore"

	data, err := os.ReadFile(gitignore)
	if err != nil {
		t.Fatalf("AC3 FAIL: cannot read .gitignore at %s: %v", gitignore, err)
	}

	content := string(data)
	if !strings.Contains(content, ".secrets/") {
		t.Errorf("AC3 FAIL: `.secrets/` is NOT listed in .gitignore — add it to prevent committing credentials")
	} else {
		t.Log("AC3 PASS: `.secrets/` is excluded in .gitignore")
	}

	// Also verify git check-ignore agrees (if git is available).
	if _, err := exec.LookPath("git"); err != nil {
		t.Log("git not available — skipping git check-ignore assertion")
		return
	}

	// Create a test file in .secrets/ to check git ignore status.
	testFile := projectRoot + ".secrets/minio_root_user"
	// Only check if the file exists (may not exist in a clean checkout).
	if _, err := os.Stat(testFile); err == nil {
		cmd := exec.Command("git", "-C", projectRoot, "check-ignore", "-q", testFile)
		if err := cmd.Run(); err != nil {
			t.Errorf("AC3 FAIL: `git check-ignore -q .secrets/minio_root_user` returned non-zero — file may not be gitignored")
		} else {
			t.Log("AC3 PASS: git check-ignore confirms .secrets/minio_root_user is ignored")
		}
	}
}

// TestMinIO_ADR013ExistsWithCredentialsWarning — AC4
//
// Given: ADR-013 is inspected
// When:  its content is read
// Then:  it exists and contains "Replace before first production start"
//
// FAILS until docs/architecture/adr/ADR-013-minio-object-storage.md is created.
func TestMinIO_ADR013ExistsWithCredentialsWarning(t *testing.T) {
	projectRoot := projectRootForMinio()
	adrPath := projectRoot + "docs/architecture/adr/ADR-013-minio-object-storage.md"

	data, err := os.ReadFile(adrPath)
	if err != nil {
		t.Fatalf("AC4 FAIL: ADR-013 not found at %s — create the ADR before implementation starts (err: %v)",
			adrPath, err)
	}

	content := string(data)
	warnPhrase := "Replace before first production start"
	if !strings.Contains(content, warnPhrase) {
		t.Errorf("AC4 FAIL: ADR-013 does not contain credentials warning %q — add it to the ADR", warnPhrase)
	} else {
		t.Log("AC4 PASS: ADR-013 exists and contains credentials warning")
	}
}

// TestMinIO_READMEHasCredentialsWarning — AC4
//
// Given: README.md is inspected
// When:  the MinIO section is read
// Then:  it contains "Replace before first production start"
//
// FAILS until README.md is updated with the MinIO section and credentials warning.
func TestMinIO_READMEHasCredentialsWarning(t *testing.T) {
	projectRoot := projectRootForMinio()
	readmePath := projectRoot + "README.md"

	data, err := os.ReadFile(readmePath)
	if err != nil {
		t.Fatalf("AC4 FAIL: cannot read README.md at %s: %v", readmePath, err)
	}

	content := string(data)
	warnPhrase := "Replace before first production start"
	if !strings.Contains(content, warnPhrase) {
		t.Errorf("AC4 FAIL: README.md does not contain credentials warning %q — add a MinIO section with the warning", warnPhrase)
	} else {
		t.Log("AC4 PASS: README.md contains credentials warning")
	}
}

// TestMinIO_NoSecretsInGitHistory — AC5
//
// Given: git log -- .secrets/ is run
// When:  the output is inspected
// Then:  no .secrets/ files have ever been committed
//
// PASSES already (gitignore was present before this story) — this is a regression guard
// that ensures no future commit accidentally includes .secrets/ files.
func TestMinIO_NoSecretsInGitHistory(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not available in PATH — skipping git history check")
	}

	projectRoot := projectRootForMinio()

	// Check if .secrets/ files have ever been committed.
	cmd := exec.Command("git", "-C", projectRoot, "log", "--oneline", "--", ".secrets/")
	out, err := cmd.Output()
	if err != nil {
		t.Skipf("git log failed (%v) — git repo may not be available in this environment", err)
	}

	output := strings.TrimSpace(string(out))
	if output != "" {
		t.Errorf("AC5 FAIL: .secrets/ files appear in git history:\n%s\n"+
			"Remove them from history and ensure .gitignore is correct.", output)
	} else {
		t.Log("AC5 PASS: no .secrets/ files in git history")
	}
}

// TestMinIO_NoBucketCredentialsHardcodedInCompose — AC2 security guard
//
// Given: docker-compose.yml is read
// When:  the content is inspected for hardcoded MinIO credentials
// Then:  no MINIO_ROOT_USER or MINIO_ROOT_PASSWORD env vars have literal values
//        (they must use secrets or environment variable references only)
//
// FAILS if developer accidentally hardcodes credentials in docker-compose.yml.
func TestMinIO_NoBucketCredentialsHardcodedInCompose(t *testing.T) {
	projectRoot := projectRootForMinio()
	composeFile := projectRoot + "docker-compose.yml"

	data, err := os.ReadFile(composeFile)
	if err != nil {
		t.Skipf("cannot read docker-compose.yml at %s: %v", composeFile, err)
	}

	content := string(data)

	// Check that MINIO_ROOT_USER and MINIO_ROOT_PASSWORD are not assigned literal values.
	// A hardcoded value would look like: MINIO_ROOT_USER: "somevalue" (not a file reference or _FILE suffix).
	// We allow: MINIO_ROOT_USER_FILE (reading from Docker secret file) or empty references.
	hardcodedPatterns := []string{
		"MINIO_ROOT_USER: minioadmin",
		"MINIO_ROOT_PASSWORD: minioadmin",
		"MINIO_ROOT_USER: admin",
		"MINIO_ROOT_PASSWORD: password",
	}

	for _, pattern := range hardcodedPatterns {
		if strings.Contains(content, pattern) {
			t.Errorf("AC2 FAIL: hardcoded MinIO credential found in docker-compose.yml: %q — "+
				"use Docker Secrets (MINIO_ROOT_USER_FILE) instead", pattern)
		}
	}

	// If MINIO_ROOT_USER appears without _FILE suffix and without a ${...} reference, it's suspicious.
	if strings.Contains(content, "MINIO_ROOT_USER:") && !strings.Contains(content, "MINIO_ROOT_USER_FILE") {
		if !strings.Contains(content, "MINIO_ROOT_USER: ${") {
			t.Logf("AC2 WARNING: MINIO_ROOT_USER found without _FILE suffix and without ${} reference — verify it uses Docker Secrets")
		}
	}

	t.Log("AC2 PASS: no obviously hardcoded MinIO credentials found in docker-compose.yml")
}
